### ISSUE TITLE
[BUG] Old reference image in "/etc/containerd/config.toml"

### ISSUE THREAD

**Issue by AciDCooL** [vmware-samples/vcenter-event-broker-appliance#1085]
**Describe the bug**
Cannot use VEBA OVA on a air gapped environment.
There is an entry in "/etc/containerd/config.toml"with an old image under the value: sandbox_image.

As a workaround I tried to fix this after deploying the appliance by:
- Changed: sandbox_image = "registry.k8s.io/pause:3.8"
- Restarted containerd: systemctl restart containerd
- reset kubeadm workspace: kubeadm reset --force

But then I need to run all the setup scripts manually and they are a bit picky about the system environment variables. I gave up on this and I'll wait until there is a new appliance with the right control plane images and references.

Also found that there are two pause images in the OVA, 3.7 and 3.8, maybe we can do with just one and a small change in the toml file. Think the file referenced version 3.6 but cant be bothered to redeploy the container again just to check for the wrong version number.
Reason this works with internet is obvious, it will download the older referenced image from the cloud. Which means when the Appliance runs it will contain 3.6, 3.7 and 3.8. And then runs 3.6. But someone with a working appliance and internet enabled could confirm this.

**To Reproduce**
Deploy OVA with air gapped network. And it fails everytime.

**Expected behavior**
Deploy OVA and have working system

**Screenshots**
n/a

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: 0.7.5

**Additional context**

**Comment by lamw** [comment]
Hi @AciDCooL - Thank you very much for reporting the issue and additional investigation. I was actually wondering why multiple pause containers were required and wasn't able to figure it out, didn't realize this came from the "default" values of containerd. This should be simple fix to point to latest (3.8)

**Comment by lamw** [comment]
@AciDCooL I've already submitted a PR to get this fixed. If you're interested, I'm building v0.7.5 release but w/this modification if you're interested in using an updated OVA? I'll share the link here shortly

**Comment by AciDCooL** [comment]
> @AciDCooL I've already submitted a PR to get this fixed. If you're interested, I'm building v0.7.5 release but w/this modification if you're interested in using an updated OVA? I'll share the link here shortly
> 
> Here's the link: [VMware_Event_Broker_Appliance_v0.7.5_airgapped.ova](https://download3.vmware.com/software/vmw-tools/veba/VMware_Event_Broker_Appliance_v0.7.5_airgapped.ova)

This makes my day, thank you very much for such a quick bug fix on the appliance! And keep up the great work.
