### ISSUE TITLE
[BUG] Images can't be pulled from ghrc. 403 Forbidden

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#1104]
**Describe the bug**
Images can't be pulled after #1100.

I'm getting a `403`

On VEBA:

```
crictl pull ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1
E0922 07:39:33.465197 1219751 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1\": failed to resolve reference \"ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1\": failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden" image="ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1"
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1": failed to resolve reference "ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1": failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

On workstation:

```
docker pull ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-pcli-tag:1.5
Error response from daemon: Head "https://ghcr.io/v2/vmware-samples/vcenter-event-broker-appliance/kn-pcli-tag/manifests/1.5": denied
```

**Comment by embano1** [comment]
@rguske I know we made that change recently, but wasn't sure we were already supposed to pull from `ghcr` instead of continuing from `gcr` until all images are pushed?

**Comment by rguske** [comment]
> @rguske I know we made that change recently, but wasn't sure we were already supposed to pull from `ghcr` instead of continuing from `gcr` until all images are pushed?

Problem is, that all function examples are already referencing `ghrc`, which will cause issues obviously.

**Comment by embano1** [comment]
Not on `master` branch though. You are deploying from `development`, correct? We haven't cut a release yet.

**Comment by rguske** [comment]
I get the point. Problem IMO is, that the development branch is default and therefore users will use it when testing VEBA/the functions. I'm sure lots of users will run into it.

**Comment by lamw** [comment]
While @embano1 is correct, I do agree that for anyone new, they'll just go straight to Development (given that's the default) to run the examples. This is on my to do list actually, to just take latest examples + router and push to ghrc, this way both should work

**Comment by lamw** [comment]
All VEBA container images have been pushed to `gchr`

```
docker pull ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1
1.1: Pulling from vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync
ba98085a824f: Pull complete
250c06f7c38e: Pull complete
4f3b649c4ee3: Pull complete
Digest: sha256:24821f45f57568eeb9b20e13f2db5c7dc1cff57e02a0b8dbe61b57948fe8ac4f
Status: Downloaded newer image for ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1
ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-go-nsx-tag-sync:1.1
```
