### ISSUE TITLE
[BUG] Unable to locate the EBA image on developer.vmware.com

### ISSUE THREAD

**Issue by revolutionlabs** [vmware-samples/vcenter-event-broker-appliance#1138]
**Describe the bug**
Unable to locate the EBA image on developer.vmware.com

**To Reproduce**
1. Go to https://flings.vmware.com/vmware-event-broker-appliance, redirects to https://developer.vmware.com/samples.
2. Search for _event broker appliance_.
3. Three entries are returned, none of which are the actual appliance.

**Expected behavior**
A download link to the EBA.

**Screenshots**
![image](https://github.com/vmware-samples/vcenter-event-broker-appliance/assets/4985651/55247fa5-3944-4777-a72d-908964270b05)

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: All

**Additional context**
Not sure if this is expected, have the standalone images been deprecated due to the retirement of flings? If so that's no awesome but some documentation stating as such. Furthermore if VMware is going to walk away from this project then some clarity would be welcome. I'd really like to continue utilizing it but unfortunately I do not have the time to maintain the code myself.

**Comment by rguske** [comment]
Hi @revolutionlabs, thanks for raising this issue. We can't share any updates on the Fling program yet. But as @lamw has written in his [article](https://williamlam.com/2023/10/vmware-flings-update.html), you can use the following link to download the VEBA appliance. 

Download VEBA: https://communities.vmware.com/t5/Flings/ct-p/77 

Thx a lot for your interest in the project. Please close the issue if the provided answer was helpful.

**Comment by lamw** [comment]
As mentioned, VMware Flings can now be found on the VMTN community. The short URL is vmwa.re/flings
