### ISSUE TITLE
VEBA root user login monitor and other user logins - Not an issue

### ISSUE THREAD

**Issue by 1MBosh** [vmware-samples/vcenter-event-broker-appliance#1152]
Hello this is not an issue --I just can't get VEBA to monitor VCSA Appliance Managemnet root logins failure 
and also Users login failures to vsphere 
I don't see these events getting logged in Sockeye so I can start getting my functions and add these into the handler file to be sent to Teams webhook --if you guys have detailed instructions how this can be done --it will be awesome! thanks!

**Comment by lamw** [comment]
If vCenter Events aren't generated, then you won't be able to subscribe and build event-driven automation :)

VAMI (e.g. https://[VC]:5480) doesn't publish events into vCenter Server, hence you're not doing anything wrong, there just aren't any events for VAMI login, especially the scenario where VC might actually be down. 

Quickly looking at my lab env, when failed VAMI logins occur, you'll find the entry in a log file `/var/log/vmware/applmgmt-audit/applmgmt-audit.log` that'll look like following:

```
2024-01-22T03:07:35.463: INFO User Password Authentication request for user : badadmin
2024-01-22T03:07:37.209: ERROR Authentication Status : Failed
```

If you've got syslog forwarding, you in theory could trap this detail else where and then use VEBA as your notification endpoint via custom function but there's no native events for VAMI logins
