### ISSUE TITLE
How to add new vCenter connection to VEBA

### ISSUE THREAD

**Issue by IdanRay** [vmware-samples/vcenter-event-broker-appliance#1189]
**Hello,**

Recently I deployed the veba 0.7.5 from ovf, and configured one vcenter.
Now I want to add one more vCenter to the veba to see on the same Sockeye the Events on two different vCenters , how can I do it ?
I tried to deploy new files for the new vCenter that I want to add:
"/root/config/event-router/vmware-event-router-config-vcenter-test.yaml"
"/root/config/event-router/vmware-event-router-k8s-vcenter-test.yaml"

commands that I run:
- kubectl -n vmware-system create secret generic vmware-event-router-config-vcenter --from-file="/root/config/event-router/vmware-event-router-config-vcenter-test.yaml"
- kubectl apply -f "/root/config/event-router/vmware-event-router-config-vcenter-test.yaml" -n vmware-system
- kubectl apply -f "/root/config/event-router/vmware-event-router-k8s-vcenter-test.yaml" -n vmware-system

This replaces the current vCenter with a new one instead of just creating a new, additional one, and I can only see the new one connected to Sockeye.

Please advise

**Comment by IdanRay** [comment]
@lamw please your help 🙏

**Comment by rguske** [comment]
Hi @IdanRay , please apologize for the late reply to your issue. Basically, we don't support a `1:n` relationship between VEBA and an event-producer. See also [FAQ](https://vmweventbroker.io/faq). However, with the introduction of the [VMware Tanzu Sources for Knative](https://vmweventbroker.io/kb/tanzu-sources) in the latest VEBA v0.8, we've made it very simple to add multiple vCenter Server (`VSphereSource`) to your VEBA instance. Check out our docs [here](https://vmweventbroker.io/kb/deploy-tanzu-sources-kind#create-a-new-vspheresource-via-cli).

**Comment by rguske** [comment]
Regarding my last comment. Please keep in mind whats stated on the docs regarding the 1:1 relationship.

> It is possible though to run multiple instances of a source (e.g. VSphereSource) with different configurations to address multi-vCenter scenarios. This decision was made for scalability and resource/tenancy isolation purposes. 

Source: [Current Limitations](https://vmweventbroker.io/kb/tanzu-sources#current-limitations)

Also, we never ran any performance tests for multi-vCenter scenarios.

**Comment by IdanRay** [comment]
@rguske thanks for your answer! 
I deployed the latest version of veba, and configure two vCenters on the veba vm. It's works ok.
I will monitor the environment to see that everything works properly and there is no effect with a connection against two vCenters.

**Comment by rguske** [comment]
Great! Please feel free to close the issue if you think it's not needed anymore.

**Comment by IdanRay** [comment]
Thanks
