### ISSUE TITLE
Optimize Installer

### ISSUE THREAD

**Issue by dcasota** [vmware-samples/vcenter-event-broker-appliance#1190]
**Is your feature request related to a problem? Please describe.**
The actual installer ( x86_64 ova) with 3.7gb is quite big. On a fresh installed VEBA, the consumption is
- 1.5gb for `io.containerd.content.v1.content` and
- 4gb for `io.containerd.snapshotter.v1.overlayfs` 
in `/var/lib/containerd`.

I came across this and wonder what happens if the unused containers are deleted with `crictl rmi --prune` ?

**Describe the solution you'd like**
grow-as-you-go with offline/online support

**Additional context**
As an inexperienced person, the architecture of Nvidia Inferencing Microservices (NIM) from os to prebuilt containers looks similar to the VEBA concept. To me, maintaining Nvidia appliances in production already seems a challenge.
The actual support is 1 vCenter = 1 VEBA, right? Are different operation modes thinkable? e.g.
- "local cacher" with multi-hub support (TanzuHub, packages.vmware.com/photon, flathub?) and local caching repository (image distribution on containerd, rpm, ...)
- VEBA converter functions: virtual hardware, mbr -> uefi, ide iso -> sata cdrom, nvme, Ph3,4 -> 5, ext4 -> btrfs/zfs file dedupe,  certs/pki/docker/runc/containerd, tdnf-automatic, photon-upgrade, ...
- VEBA applicance inplace upgrade

**Comment by rguske** [comment]
Hi @dcasota, thanks for your interest and shared thoughts. However, I struggle to follow you on multiple points. Could you please be more precise on:

> "local cacher" with multi-hub support (TanzuHub, packages.vmware.com/photon, flathub?) and local caching repository (image distribution on containerd, rpm, ...)

Which problem do you try to solve with it?

> VEBA converter functions: virtual hardware, mbr -> uefi, ide iso -> sata cdrom, nvme, Ph3,4 -> 5, ext4 -> btrfs/zfs file dedupe, certs/pki/docker/runc/containerd, tdnf-automatic, photon-upgrade, ...

Is this a suggestion for a new function?

Regarding:

> VEBA applicance inplace upgrade

This is and will not be supported. New versions of VEBA (appliance form-factor) will ship new versions of the internal components.

Regarding multi-vcenter support, please have a look at issue #1189

**Comment by dcasota** [comment]
Hi @rguske, sorry for the struggle. This was definitely not my intention. The writing of 'additional context' happened in a phase of reflecting about housekeeping tools. At that time Nvidia Containers with VEBA functionality looked like a good combo. 

Nvidia containers are published with an Ubuntu basis and are not inplace upgradable. As customer, you have to install a new version and proceed a migration. There is no tdnf, tdnf-automatic, photon-upgrade, etc.  With filter expression e.g. 'broke' in search forums.developer.nvidia.com you get an idea about the demand.

-> close ticket.
