### ISSUE TITLE
[BUG] VEBA builds failing due to replacement of projects.registry.vmware.com

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#1234]
**Describe the bug**
Due to the replacement of VMware's Harbor registry `projects.registry.vmware.com`, the appliance build fails due to wrong image references for the images:

* projects.registry.vmware.com/veba/veba-ui:c2eecec0
* projects.registry.vmware.com/veba/kn-echo:latest
* projects.registry.vmware.com/veba/tinywww:latest
* projects.registry.vmware.com/veba/ce-pcli-base:latest

Antrea:
* projects.registry.vmware.com/antrea/antrea-agent-ubuntu:v1.15.0
* projects.registry.vmware.com/antrea/antrea-controller-ubuntu:v1.15.0
Antrea related issue: [#6003](https://github.com/antrea-io/antrea/issues/6003)

**Comment by rguske** [comment]
For Antrea, it is now just:
* antrea/antrea-agent-ubuntu:v1.15.0
* antrea/antrea-controller-ubuntu:v1.15.0

**Comment by lamw** [comment]
Thanks for reporting @rguske 

ce-pcli-base is actually already on ghcr `https://github.com/orgs/vmware-samples/packages/container/package/vcenter-event-broker-appliance%2Fce-pcli-base`

Let me look at getting the others images above into ghcr as well

**Comment by lamw** [comment]
Done!

- ghcr.io/vmware-samples/vcenter-event-broker-appliance/veba-ui: c2eecec0
- ghcr.io/vmware-samples/vcenter-event-broker-appliance/tinywww:latest
- ghcr.io/vmware-samples/vcenter-event-broker-appliance/kn-echo:latest

**Comment by rguske** [comment]
> https://github.com/orgs/vmware-samples/packages/container/package/vcenter-event-broker-appliance%2Fce-pcli-base

@lamw It's an invalid image reference. Could you please give me the correct reference?

**Comment by lamw** [comment]
> > https://github.com/orgs/vmware-samples/packages/container/package/vcenter-event-broker-appliance%2Fce-pcli-base
> 
> @lamw It's an invalid image reference. Could you please give me the correct reference?

That's because what I shared was simply the URL to the container image under `Packages` in repo :)

You can get the full path by going to the URL, which is following:
```
ghcr.io/vmware-samples/vcenter-event-broker-appliance/ce-pcli-base:latest
```

**Comment by rguske** [comment]
> > > https://github.com/orgs/vmware-samples/packages/container/package/vcenter-event-broker-appliance%2Fce-pcli-base
> > 
> > 
> > @lamw It's an invalid image reference. Could you please give me the correct reference?
> 
> That's because what I shared was simply the URL to the container image under `Packages` in repo :)
> 
> You can get the full path by going to the URL, which is following:
> 
> ```
> ghcr.io/vmware-samples/vcenter-event-broker-appliance/ce-pcli-base:latest
> ```

🤣 right! Too late here already.
