### ISSUE TITLE
Fix Event Router tag from "0.x.y" to "v0.x.y" 

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#163]

**Comment by embano1** [comment]
@lamw just checked the code and it looks like the event router Makefile pulls from .veba.version (BOM) which is already using semver (v.X.Y.Z). So we should be good here. Or was this issue related to the pre-release where we currently create a router image with $COMMIT as tag?

**Comment by embano1** [comment]
Update: the `tag` used when pushing a pre-release image via Github Actions is the name of the branch, e.g `release-0.4`. Any suggestion how we should handle this when testing the pre-release, incl. building the appliance, etc. if this is not working for the appliance built scripts?

**Comment by embano1** [comment]
Discussed with @lamw that we'll use the following convention in the BOM in the future for the appliance/router builds (using examples):

`".veba.version"` => `["v0.5.0","release-0.5.0","development"]`
`"vmware-event-router.version"` => `["v0.5.0","release-0.5.0","development"]`
`"vmware-event-router.containers[0].version"` => `["v0.5.0","release-0.5.0","development"]`

`master` branch will be reflected using a stable tag, e.g. `v0.5.0`
Any `release-` branch will be reflected using `release-<version>` omitting `v` for backwards-compat reasons, e.g. `release-0.5.0`
Router image tags, based on the branch where changes are pushed to, will use `<image>:v0.5.0` for `master`, `<image>:release-0.5.0` for `release-<version>` and `<image>:development` on every push to `development` branch. In addition, the `master` and `development` container images will also be tagged with the corresponding `COMMIT_ID` of the pushed commit.
