### ISSUE TITLE
Break up the NewAWSEventBridgeProcessor() constructor

### ISSUE THREAD

**Issue by codegold79** [vmware-samples/vcenter-event-broker-appliance#168]
The construction function for a new AWS event bridge processor has gotten quite long and has many different types of operations in it, some of which are repeated in the syncRules process.

One suggestion to follow might be putting the section finding the ARN rules in a separate function. 

@embano1 had this suggestion, "...breaking out the options handling and pattern match logic into helpers makes sense, especially since the syncRules has a lot of repetitive code here."

Since this issue requires re-organization and no additional logic, and there are tests to ensure the code didn't break completely, I believe it's a good first issue for those new to this code base.

**Acceptance Criteria**
- [ ] reduce the number of responsibilities the constructor has to do by breaking processes out to different functions
- [ ] make the code more readable by moving responsibilities out to different function(s)
- [ ] tests pass after change

**Comment by embano1** [comment]
🙏 Thank you for flagging this!
