### ISSUE TITLE
Non-standard use of "subject" in CloudEvents Spec

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#182]
**Is your feature request related to a problem? Please describe.**
As of today the use of `type` and `subject` in the CloudEvents structured event payload might not conform to what users expect. E.g. `"com.vmware.event.router/event"` can be considered an abstract event class and the corresponding event used in `subject`, e.g. `VmPoweredOnEvent` is not really a subject as per the meaning of the spec.

**Describe the solution you'd like**
Instead of this:

```json
{
  "id": "08179137-b8e0-4973-b05f-8f212bf5003b",
  "source": "https://vcenter-01:443/sdk",
  "specversion": "1.0",
  "type": "com.vmware.event.router/event ",
  "subject": "VmPoweredOnEvent",
  "time": "2020-02-11T21:29:54.9052539Z"
}
```

Use:

```json
{
  "id": "08179137-b8e0-4973-b05f-8f212bf5003b",
  "source": "https://vcenter-01:443/sdk",
  "specversion": "1.0",
  "type": "com.vmware.event.router/vmware/vcenter/VmPoweredOnEvent",
  "subject": "vm-01",
  "time": "2020-02-11T21:29:54.9052539Z"
}
```

Where the syntax for `type` can be defined as:

`com.vmware.event.router/<vendor>/<provider>/<event>`

**Additional context**
Breaking change with an option to provide backward compatibility for some time (deprecation notice).

**Comment by embano1** [comment]
Figuring out a subject that can be easily constructed across different providers might not be easy. A intermediary solution would be to use the event ID/UUID as the subject.

**Comment by embano1** [comment]
Comparison of CloudEvents generated by the VMware Event Router used currently in this project vs [vSphere Sources for
Knative](https://github.com/vmware-tanzu/sources-for-knative):

| CE Property           | Type      | Required | Event Router                                                                             | vSphere Sources                                      |
|-----------------------|-----------|----------|------------------------------------------------------------------------------------------|------------------------------------------------------|
| ID                    | string    | yes      | [uuidv4](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)) | VC Event Key                                         |
| Type                  | `string`  | yes      | `com.vmware.event.router/[event\|eventex\|extendedevent]`                                | `com.vmware.vsphere.[ReflectEventName\|EventTypeID]` |
| Source                | string    | yes      | `vcenter.URI()`                                                                          | `vcenter.URI()`                                      |
| Subject               | string    | no       | `ReflectEventName\|EventTypeID`                                                          | (unused)                                             |
| datacontenttype       | string    | no       | `application/json`                                                                       | `application/xml`                                    |
| time                  | timestamp | no       | `time.Now().UTC()`                                                                       | `GetEvent().CreatedTime`                             |
| CE transport encoding | n/a       | n/a      | configurable (per processor)                                                             | binary                                               |

**Comment by vaikas** [comment]
@embano1 You added the datacontenttype overrides, so at least that field could now be updated for json/xml?
Also, would you mind adding a pointer or example on what ReflectEventName looks like.

**Comment by embano1** [comment]
> @embano1 You added the datacontenttype overrides, so at least that field could now be updated for json/xml?

Wow, you're fast! Once I'm back on my laptop I'll do as my iPad Github app keeps crashing when I try to edit that comment :D

> Also, would you mind adding a pointer or example on what ReflectEventName looks like.

Yeah, sorry for being too brief there. For "core" events such as `VmPoweredOnEvent`, i.e. those not belonging to `EventEx` or `ExtendedEvent` we use go type reflection on the `BaseEvent` interface to retrieve the event name. That's what I meant there.

**Comment by vaikas** [comment]
Oh no rush :) I was just playing with octobox (👍 so far) and noticed this lol :) 

Ok, sweet, thanks!

**Comment by embano1** [comment]
Updated the table with the recent changes in the `router` to be more aligned with `VSphereSources`. Since the `VSphereSources` format correctly represents the CloudEvents spec, it makes sense to slowly transition the `router` event schema (metadata) to the `VSphereSources` approach.

This would lead to a breaking change for existing users (triggers and code if they use these fields in their functions), so we can do a slow migration:

1) Communicate the changes upfront to prepare the user base
1) Change `type` to what `VSphereSources` uses but keep `subject` (as most users trigger on `subject` in VEBA)
1) Eventually phase out `subject` (hoping that most users would have migrated to the `type` trigger before)

**Comment by lamw** [comment]
#1075
