### ISSUE TITLE
Hostmaint-alarms fails on hosts where the cluster name contains a hyphen with a preceeding space

### ISSUE THREAD

**Issue by BristleBeard** [vmware-samples/vcenter-event-broker-appliance#196]
**Bug Description**
If a cluster name has a space followed by a hyphen, the cluster name isn't being passed to the script in a way that prevents the script from thinking argument switches are being used.

If a host has a hyphen in it's hostname, an error is thrown when an exit or enter event is processed. It appears the command line for powershell may be interpreting the hyphens as command line switches. The exact error:

**Steps to reproduce the behavior:**
1. Place a host in a cluster named similar to "AAA201 - LAB"  into maintenance mode. The following error would occur:
> /root/function/script.ps1 : Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
> + CategoryInfo          : InvalidArgument: (:) [script.ps1], PSArgumentException
> + FullyQualifiedErrorId : Argument,script.ps1
2. Place a host in a cluster named similar to "AAA201 -LAB" into maintenance mode. The following error would occur:
> ConvertFrom-Json : Conversion from JSON failed with error: Invalid character after parsing property name. Expected ':' but got: {. Path 'data.ComputeResource.Name', line 3, position 0.
> At /root/function/script.ps1:9 char:17
> + $json = $args | ConvertFrom-Json
> +                 ~~~~~~~~~~~~~~~~
> + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
> + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
> 
> DEBUG: json=""
> Connecting to vCenter Server ...
> 
> Get-View : 08/25/2020 16:04:54  Get-View                View with Id  '-' was not found on the server(s).
> At /root/function/script.ps1:26 char:14
> + $hostMoRef = Get-View $moRef
> +              ~~~~~~~~~~~~~~~
> + CategoryInfo          : ObjectNotFound: (:) [Get-View], VimException
> + FullyQualifiedErrorId : Core_GetView_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.DotNetInterop.GetVIView

3. Place a host in a cluster named similar to "AAA201- LAB" into maintenance mode. Script executes as expected.
4. Place a host in a cluster named similar to "AAA201-LAB" into maintenance mode. Script executes as expected.

**Expected behavior**
The name of the cluster being passed along should be enveloped to prevent spaces and hyphens from being evaluated as arguments. 

**Version:**
 - VEBA Form Factor: Appliance
 - VEBA Version: v0.4.1

**Comment by kremerpatrick** [comment]
I had v0.4.0 already deployed and I can reproduce the error. Investigating further.

**Comment by kremerpatrick** [comment]
Removing stale label.

**Comment by embano1** [comment]
Related #209 (we'll create a dedicated PS/PCLI template to fix this bug across all examples)

**Comment by rctunisi** [comment]
got the same exact issue on VMs and the tagging example. Appearently, the payload that comes from the event router is using CRLF instead of the normal spaces inside the json.data

i managed to get the tagging to work changing the script with a simple replace at the vmName and rebuilding the dockerfile into a new image. If anyone willing to try it out, just change the image on stack.yml to rctunisi/veba-powercli-tag-fixed:latest

**Comment by embano1** [comment]
@lamw FYI

**Comment by embano1** [comment]
@kremerpatrick I know you were working on this (PR closed though). Is this fixed?

**Comment by kremerpatrick** [comment]
It was closed without merging and I'm not sure I remember why. There was discussion on fixing it at the OpenFaaS level but I don't think it went anywhere.

**Comment by lamw** [comment]
Closing per last comment
