### ISSUE TITLE
Fix fprocess variable in template.yml for all PowerCLI functions

### ISSUE THREAD

**Issue by kremerpatrick** [vmware-samples/vcenter-event-broker-appliance#198]
**Describe the bug**

The bug reported in issue #196 can happen in any of the PowerCLI functions

template.yml must be changed in each function and tested
- fprocess: xargs pwsh ./function/script.ps1
+ fprocess: xargs -0 -I '{}' pwsh ./function/script.ps1 "'{}'"

**Comment by embano1** [comment]
Should we build our own custom PCLI template?

**Comment by embano1** [comment]
Related #196
