### ISSUE TITLE
FAQ Documentation Errata

### ISSUE THREAD

**Issue by Kyleset** [vmware-samples/vcenter-event-broker-appliance#204]
FAQ Documentation "bug"

Errata: On the following FAQ: (https://vmweventbroker.io/kb/troubleshoot-appliance) it mentions to:
vi /root/event-router-config.json

that isn't the right place. it is:
vi /root/config/event-router-config.json

**Comment by rguske** [comment]
Hi @Kyleset - thanks for pointing this out. The errata will be fixed with #195.

**Comment by Kyleset** [comment]
Not a problem. Moving from being a customer to a partner here in about a week. Expect more input from me in the future.
