### ISSUE TITLE
Clarify DNS settings in the OVF

### ISSUE THREAD

**Issue by kremerpatrick** [vmware-samples/vcenter-event-broker-appliance#21]
I don't think this code exists in the repo so I can't make a change myself. But I'm happy to do it if somebody points me in the right direction.

When the appliance is packaged, I'm suggesting a simple change to the DNS section. It should read:

DNS Servers (space separated)

If you input comma-separated DNS values, the appliance fails initial configuration because it can't do DNS lookups

**Comment by lamw** [comment]
FYI - This enhancement has been added to latest build I'm working on. 

<img width="1031" alt="Screen Shot 2019-12-16 at 12 46 10 PM" src="https://user-images.githubusercontent.com/602199/70941825-2d48f180-2002-11ea-91b9-49acb917b481.png">
