### ISSUE TITLE
Appliance deployed with proxy config needs reboot/docker restart

### ISSUE THREAD

**Issue by dsbibby** [vmware-samples/vcenter-event-broker-appliance#211]
**Describe the bug**
After deploying the VEBA appliance with proxies configured, docker cannot pull images from internet based image repositories unless either the docker service is restarted or the appliance rebooted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy the VEBA appliance specifying a valid proxy config
2. Attempt to deploy the `veba-echo` example function
3. Function will fail to deploy with `ErrImagePull` in the output of `kubectl get pods -A`
![Screenshot 2020-10-03 at 09 01 35](https://user-images.githubusercontent.com/17053612/94986963-ddb8bf80-055a-11eb-9efd-6d170d088f73.png)
4. Reboot the appliance/run `systemctl restart docker.service`
5. Function will automatically deploy successfully

**Expected behaviour**
A reboot shouldn't be required and functions should deploy correctly straight after appliance deployment.

**Screenshots**

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: v0.4.1

**Additional context**

**Comment by kremerpatrick** [comment]
Fresh 0.4.1 deployment.

Docker pull fails
root@veba04 [ ~ ]# docker pull hello-world
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

curl succeeds
root@veba04 [ ~ ]# curl http://www.google.com
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; 

Tested both echo and pytag function, both fail with ImagePullBackoff
root@veba04 [ ~ ]# kubectl get pods -A
NAMESPACE        NAME                                   READY   STATUS             RESTARTS   AGE
kube-system      antrea-agent-8glk8                     2/2     Running            0          44m
kube-system      antrea-controller-78d8dbd4fb-lbqlx     1/1     Running            0          44m
kube-system      coredns-6dcc67dcbc-7nbnk               1/1     Running            0          44m
kube-system      coredns-6dcc67dcbc-hr9ql               1/1     Running            0          44m
kube-system      etcd-veba04                            1/1     Running            0          43m
kube-system      kube-apiserver-veba04                  1/1     Running            0          43m
kube-system      kube-controller-manager-veba04         1/1     Running            0          43m
kube-system      kube-proxy-cv96x                       1/1     Running            0          44m
kube-system      kube-scheduler-veba04                  1/1     Running            0          43m
openfaas-fn      pytag-fn-df8cfdb9f-sqf57               0/1     ImagePullBackOff   0          2m34s
openfaas-fn      veba-echo-67ccc58456-95bv9             0/1     ImagePullBackOff   0          7m
openfaas         alertmanager-58f8d787d9-fqw7v          1/1     Running            0          43m
openfaas         basic-auth-plugin-dd49cd66b-psmfc      1/1     Running            0          44m
openfaas         faas-idler-59ff9778fd-f4vkp            1/1     Running            3          44m
openfaas         gateway-74f6f9489b-dkq9j               2/2     Running            2          44m
openfaas         nats-6dfbf45d77-zw2gq                  1/1     Running            0          43m
openfaas         prometheus-5f5494b54f-bjjxd            1/1     Running            0          44m
openfaas         queue-worker-59b67bf4-bkhf6            1/1     Running            2          43m
projectcontour   contour-5cddfc8f6-4wz7d                1/1     Running            0          43m
projectcontour   contour-5cddfc8f6-m98nr                1/1     Running            0          44m
projectcontour   contour-certgen-d4c4p                  0/1     Completed          0          44m
projectcontour   envoy-ks6hl                            1/1     Running            0          43m
vmware           tinywww-7fcfc6fb94-6c4jf               1/1     Running            0          44m
vmware           vmware-event-router-587977459d-drjbl   1/1     Running            3          44m

kubectl describe pod shows errors:
  Warning  Failed     5m5s (x4 over 7m32s)    kubelet, veba04    Failed to pull image "vmware/veba-python-echo:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Docker pull immediately succeeds after restarting docker service

root@veba04 [ ~ ]# systemctl restart docker.service
root@veba04 [ ~ ]# docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:4cf9c47f86df71d48364001ede3a4fcd85ae80ce02ebad74156906caff5378bc
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest

Function pods eventually fix themselves.

root@veba04 [ ~ ]# kubectl get pods -A
NAMESPACE        NAME                                   READY   STATUS      RESTARTS   AGE
kube-system      antrea-agent-8glk8                     2/2     Running     2          52m
kube-system      antrea-controller-78d8dbd4fb-lbqlx     1/1     Running     1          52m
kube-system      coredns-6dcc67dcbc-7nbnk               1/1     Running     1          52m
kube-system      coredns-6dcc67dcbc-hr9ql               1/1     Running     1          52m
kube-system      etcd-veba04                            1/1     Running     1          51m
kube-system      kube-apiserver-veba04                  1/1     Running     1          51m
kube-system      kube-controller-manager-veba04         1/1     Running     1          51m
kube-system      kube-proxy-cv96x                       1/1     Running     1          52m
kube-system      kube-scheduler-veba04                  1/1     Running     1          51m
openfaas-fn      pytag-fn-df8cfdb9f-sqf57               1/1     Running     1          10m
openfaas-fn      veba-echo-67ccc58456-95bv9             1/1     Running     0          15m
openfaas         alertmanager-58f8d787d9-fqw7v          1/1     Running     1          51m
openfaas         basic-auth-plugin-dd49cd66b-psmfc      1/1     Running     1          52m
openfaas         faas-idler-59ff9778fd-f4vkp            1/1     Running     6          52m
openfaas         gateway-74f6f9489b-dkq9j               2/2     Running     6          52m
openfaas         nats-6dfbf45d77-zw2gq                  1/1     Running     1          51m
openfaas         prometheus-5f5494b54f-bjjxd            1/1     Running     1          52m
openfaas         queue-worker-59b67bf4-bkhf6            1/1     Running     5          51m
projectcontour   contour-5cddfc8f6-4wz7d                1/1     Running     1          51m
projectcontour   contour-5cddfc8f6-m98nr                1/1     Running     1          52m
projectcontour   contour-certgen-d4c4p                  0/1     Completed   0          52m
projectcontour   envoy-ks6hl                            1/1     Running     1          51m
vmware           tinywww-7fcfc6fb94-6c4jf               1/1     Running     1          52m
vmware           vmware-event-router-587977459d-drjbl   1/1     Running     6          52m
