### ISSUE TITLE
Add ability to build VEBA appliance using the development branch of VMware Event Router 

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#225]
**Is your feature request related to a problem? Please describe.**
Yes, from a development point of view. Today, the VEBA appliance is built by passing in either `release` or `master` flag into the build.sh script which is then used to locate the apprioroiate version of the VMware Event Router container. This works for doing a GA or Release build BUT does not take into considerations on-going development and causes issues that can and has broken the build. 

**Describe the solution you'd like**
To solve this problem, we'd like to introduce the `development` keyword into the build.sh which would allow someone to build the VEBA appliance using the latest development branch of the VMware Event Router which is automatically being produced for each successful checkin. 

Secondly, we're also going to change the VMware Event Router version in the veba-bom.json file to specify the `development` tag which is being applied to the VMware Event Router container when its built from Development branch and ensures for local development builds, we can get the latest version and still ensure we've got a fully functional VEBA appliance for testing purposes

**Describe alternatives you've considered**
The current alternative is manual which is hacking up your local build and identifying the specific ID of the latest VMware Event Router. This is not a scalable solution compared to the proposed solution

**Additional context**
N/A

**Comment by embano1** [comment]
> In the VEBA BOM, the vmware-event-router section will be moved up to the top for ease of editing

We just have to verify this whenever we change/reformat the file as these plugins will likely reorder the BOM
