### ISSUE TITLE
Cloud Events spec link broken

### ISSUE THREAD

**Issue by dsbibby** [vmware-samples/vcenter-event-broker-appliance#238]
**Describe the bug**
The link to the cloudevents spec on the website [here](https://vmweventbroker.io/kb/eventspec) is broken

**To Reproduce**
1. Go to link above and click Cloudevents link
2. Get Github 404 page

**Expected behavior**
Should this link to https://github.com/cloudevents/spec/blob/v1.0/spec.md

**Screenshots**

**Version (please complete the following information):**
 - VEBA Form Factor: [e.g. Appliance or K8s]
 - VEBA Version: [e.g. v0.4.0]

**Additional context**

**Comment by embano1** [comment]
Thx @dsbibby ! @pksrc can you PTAL?
