### ISSUE TITLE
Stricter Release Management

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#25]
The project is growing with more users and contributors. In order to ensure a good user experience, i.e. don't break installations due to out of sync master/release, we need to improve our release process. 

I propose a Github dev/release process as described in the diagram below (details [here](https://github.com/mobify/branching-strategy/blob/master/release-deployment.md#create-and-deploy-a-release)):
![image](https://user-images.githubusercontent.com/15986659/71077103-17186e00-2187-11ea-8446-8ceb3404347d.png)

Detailed writeup of the diagram above [here](https://nvie.com/posts/a-successful-git-branching-model/).

The following changes to the repository structure/documentation are required:

- [x] Create "development" branch - @embano1 
- [x] Update contributors guide with PR instructions - @embano1
- [x] Create PR template for contributors - @embano1
- [ ] Automated appliance deployment - @lamw 
- [ ] Automated regression tests (deploy appliance, test a set of function) - @lamw 

Please provide feedback/missing action items so we can start with a more streamlined release process.

@lamw @vladi-velikov @martindekov

**Comment by lamw** [comment]
I'm currently updating all example README to reflect our discussion of checking out `development` branch as part of running through the examples. I noticed we don't have any consistency on the README as well, so we may want to create a template for that. You can assign that to me

**Comment by martindekov** [comment]
So we keep `master` stable. When we start developing we checkout master in `develop` branch. Every contribution(pull request) happens against that `develop` branch. Once we decide that it is time to cut a release the develop branch is merged into `master` and then new develop is checked out from `master` to continue development?

I just want to make sure I understood it correct. Otherwise it seems like a pretty good developing strategy :+1:

**Comment by embano1** [comment]
@martindekov Yes, that's what I would like to suggest and thx for the feedback.
Just updated initial comment: created a `development` branch (also default branch now). We don't need a `release` branch as we would just tag the `development` branch for a certain release at a given commit and then merge into `master` (so `master` always reflects the latest stable release). Since `development` is the default branch we don't need to check out from `master` after tagging/merging a release into the `master`. Sounds good?

**Comment by embano1** [comment]
Some useful references for automating builds (especially `go` related) and creating changelogs:

`govmomi`: https://github.com/vmware/govmomi/pull/1375
Changelog generator: https://github.com/git-chglog/git-chglog/
`ir2proxy`: https://github.com/projectcontour/ir2proxy

**Comment by embano1** [comment]
Closing this one as we will have unit/integration tests for the event router bits and automating the appliance build is too much effort for now.
