### ISSUE TITLE
OpenFaaS Go template can use Go modules

### ISSUE THREAD

**Issue by alexellis** [vmware-samples/vcenter-event-broker-appliance#271]
The examples in the repo using Go appear to be using vendoring, but Go modules has been supported for some time in the templates and CLI.

Example from the VEBA samples repo:

https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/master/examples/go/tagging

See here for docs:

https://docs.openfaas.com/cli/templates/#go-golang-http-of-watchdog-template

Feel free to ask questions.

**Comment by lamw** [comment]
Thanks for the suggestion Alex. We'll keep this under consideration in future planning.
