### ISSUE TITLE
faas-cli generate command for your new event processor

### ISSUE THREAD

**Issue by alexellis** [vmware-samples/vcenter-event-broker-appliance#272]
I noticed that Knative has been added as an event processor. 

Rather than rebuilding all your examples, you may find the following command useful for Knative users:

```bash
faas-cli new --lang go tester
faas-cli generate --api serving.knative.dev/v1 --f tester.yml

---
apiVersion: serving.knative.dev/v1
kind: Function
metadata:
  name: tester
  namespace: openfaas-fn
spec:
  name: tester
  image: tester:latest
```

It also supports mapping of labels, annotations, env-vars and secrets in the generated CRs.

A useful workflow can be : `faas-cli generate | kubectl apply -f -`

It seems like something that would be valuable to you given your adoption and use of the OpenFaaS codebase in this project.

Have a look at Carlos Santana's example repo which I helped him create after a conversation at KubeCon: [knative-faas-cli](https://github.com/csantanapr/knative-faas-cli)

@lamw @embano1 you're welcome to participate in the community, lots has changed over the past two years.

**Comment by lamw** [comment]
Thanks for sharing Alex. We'll keep this in mind in future planning.
