### ISSUE TITLE
[Feature] build the event router image for ARM

### ISSUE THREAD

**Issue by vrabbi** [vmware-samples/vcenter-event-broker-appliance#287]
**Is your feature request related to a problem? Please describe.**
As ARM based solutions are growing including the ESXi on ARM fling having the event router be able to be deployed on ARM would be very beneficial. I have a few K3s clusters running on RPIs and also think that now the running K8s on Graviton instances on AWS is possible (using KOPS), that for use cases of VMC this could also be relevant. 

**Describe the solution you'd like**
As discussed over slack, i want to be able to run VEBA on my RPI ESXi cluster in a k3s cluster i have running. 
Michael Gasch mentioned that it should work as the go binary for the event router can be compiled for any architecture.

**Describe alternatives you've considered**
I have considered building from source and compiling the binary on my own to ARM but would much rather not deviate from the official images,

**Comment by lamw** [comment]
Verified @embano1 [Arm64 image of VMware Event Router](http://embano1/router-c3dac096cdb7ad9fe1a56bb4ab9fc5d) (full details at https://www.virtuallyghetto.com/2021/01/veba-knative-k3s-on-esxi-arm.html)

**Comment by vrabbi** [comment]
@lamw that is awesome! Thanks for all the work you put into this and on the great blog post! This is in my list of things to do this weekend for sure!
