### ISSUE TITLE
VEBA Appliance stop work when disk 90 percent full

### ISSUE THREAD

**Issue by allankjaer** [vmware-samples/vcenter-event-broker-appliance#294]
**Describe the bug**
VEBA Appliance stops working after +22 days, the / mount was 90 percent full, I found that the file /var/log/conntrackd-stats.log was over 5 GB, I just deleted this and deleted all Evicted pods and rebooted.

**To Reproduce**
1) run "dd if=/dev/zero of=/var/log/large-file.log bs=4k iflag=fullblock,count_bytes count=6G" to create a large file
2) kubectl get pods -A
3) Look for pods that get Evicted, for all namespaces other then "kube-system"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/65256499/107112967-c0269a00-685b-11eb-885d-01406e8bc43c.png)

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: 0.5.0
 - Using build in openfaas

**Additional context**

**Comment by lamw** [comment]
Thank you @allankjaer for reporting this. 

Just doing a quick search online, it looks like the conntrackd service does NOT implement log rotate by default :/

At a minimum, we'll implement the log rotation as mentioned https://gitlab.alpinelinux.org/alpine/aports/-/issues/12333 and possibly also disable stats logging as we have no use for that information

**Comment by allankjaer** [comment]
I tried to enable log rotation but it did not work.
I think it uses "cron" for the log rotation, and that is not installed/enabled on the VEBA appliance.

**Comment by lamw** [comment]
@allankjaer logrotate runs daily via cron, so you won't see it immediately after making change. You can manually run it like I showed in PR
