### ISSUE TITLE
Non ISO compliant Datetime String in Event-Data

### ISSUE THREAD

**Issue by sp-schoen** [vmware-samples/vcenter-event-broker-appliance#300]
**Describe the bug**
For my application I parse the CreatedTime-Field in the Event-Data to a Python Datetime object. But Today I got an error while parsing the following datetime: '2021-02-09T12:24:39.14' (I already strip the trailing 'Z').
As you can see, there is missing also a '0' at the end. After I add this manually, I could parse the String successfully.

**To Reproduce**
Nothing special, just run the event-router

**Expected behavior**
In the CreatedTime-Field is always a datetime string in ISO-Format.

**Version (please complete the following information):**
 - VEBA Form Factor: K8s
 - VEBA Version: v0.5.0

**Comment by embano1** [comment]
Thx @sp-schoen for bringing this to our attention! Just to clarify, the issue is with `event.Data.CreatedTime` and not with `event.Time`?

**Comment by sp-schoen** [comment]
@embano1 Yes, that is correct.

**Comment by embano1** [comment]
This timestamp comes straight from vCenter. IIUC you're missing the time offset, right? I think ISO time allows for special UTC encoding without offset when Z is appended. So why do you have to strip the Z?

**Comment by sp-schoen** [comment]
The Python datetime library doesn't accept a datetime string with 'Z' at the end. Probably I should look for another library to parse the timestamp. I looked up the ISO 8601 (https://de.wikipedia.org/wiki/ISO_8601) and this here is actually a valid timestamp.

**Comment by embano1** [comment]
Yeah, I think this is then related to Python. Is it ok to close this issue then?

**Comment by sp-schoen** [comment]
I will close it.

**Comment by dsbibby** [comment]
@sp-schoen If you haven't already, maybe take a look at using python-dateutil
`from dateutil.parser import isoparse
...
Date Time = isoparse(isodate)`

I've used this successfully in my functions to parse the dates received from vCenter.

**Comment by sp-schoen** [comment]
@dsbibby 
Thank you for your suggestion. I also had this in my mind. Nice to hear that it will work.
