### ISSUE TITLE
Change vmware namespace to vmware-system

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#311]
**Is your feature request related to a problem? Please describe.**
The deployed VMware components in VEBA are all system related. A convention is to use <name>-system for such components.

**Describe the solution you'd like**
Change `vmware` namespace to `vmware-system`

**Describe alternatives you've considered**
Keep as is.

**Additional context**
n/a

**Comment by lamw** [comment]
I'd also like to propose that we add `vmware-functions` namespace to contain all functions that'll be deployed by end-users as it pertains to Knative
