### ISSUE TITLE
Annotate Knative Service/Triggers with app:veba-ui

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#337]
**Describe the bug**
With the introduction of the Sockeye service which includes a Knative Trigger which does not contain a filter, this unintentionally causes the VEBA UI to miss-behaves as it expects trigger to always contain filter. Simple fix is to apply app:veba-ui label just like we do for secrets, to only display things created from within the VEBA UI and/or manually label as such

**Comment by embano1** [comment]
Can this be closed?
