### ISSUE TITLE
Helm cannot deploy v0.6.0: failed to create: Secret "sh.helm.release.v1.veba.v1" is invalid

### ISSUE THREAD

**Issue by lrivallain** [vmware-samples/vcenter-event-broker-appliance#355]
**Describe the bug**
When deploying v0.6.0 through `helm`, there is an issue about `invalid data` and a secret data beeing to long.

It is not related to the specific configuration I use because I was able to reproduce the issue with the `values.yaml` file provided as sample/reference.

**To Reproduce**
```bash
helm pull vmware-veba/event-router --untar
cd event-router
helm install -n vmware --create-namespace veba vmware-veba/event-router -f values.yaml --version 0.6.0
Error: create: failed to create: Secret "sh.helm.release.v1.veba.v1" is invalid: data: Too long: must have at most 1048576 bytes
```

**Expected behavior**
I was expecting the same behavior than v0.5.0:

```
helm install -n vmware --create-namespace veba vmware-veba/event-router -f values.yaml --version 0.5.0
NAME: veba
LAST DEPLOYED: Wed Apr 28 08:09:45 2021
NAMESPACE: vmware
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Version (please complete the following information):**
 - VEBA Form Factor: K8s, helm chart
 - VEBA Version: v0.6.0

**Additional context**

I think that the issue is related to the way the chart folder is build in the repository. It seems that the `releases` folder content is included in each build and result in a growing `.tgz` file.

```bash
du -sh vmware-event-router/chart/releases/*
28K     vmware-event-router/chart/releases/event-router-v0.4.1-devel.tgz
64K     vmware-event-router/chart/releases/event-router-v0.4.2-devel.tgz
96K     vmware-event-router/chart/releases/event-router-v0.5.0-pre-release.tgz
188K    vmware-event-router/chart/releases/event-router-v0.5.0.tgz
372K    vmware-event-router/chart/releases/event-router-v0.6.0-pre-release.tgz
1,5M    vmware-event-router/chart/releases/event-router-v0.6.0.tgz
```

When looking into `event-router-v0.6.0.tgz` we have previous releases embedded:

```bash
tar -xzf event-router-v0.6.0.tgz
du -sh event-router/releases/*
28K     event-router/releases/event-router-v0.4.1-devel.tgz
64K     event-router/releases/event-router-v0.4.2-devel.tgz
96K     event-router/releases/event-router-v0.5.0-pre-release.tgz
188K    event-router/releases/event-router-v0.5.0.tgz
372K    event-router/releases/event-router-v0.6.0-pre-release.tgz
744K    event-router/releases/event-router-v0.6.0.tgz
```

Until v0.6.0 the size was still compatible with "per-secret size limit of 1MB" (https://kubernetesbyexample.com/secrets/ ) but not anymore.

Adding the `releases/*.tgz` line to `.helmignore` file seems to fixe the issue:

```bash
tail -n1 .helmignore
releases/
```
```bash
helm install -n vmware --create-namespace veba . -f values.yaml --version 0.6.0
NAME: veba
LAST DEPLOYED: Wed Apr 28 08:44:48 2021
NAMESPACE: vmware
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by embano1** [comment]
Thx a ton for filing the issue and the detailed analysis! Looks like you're up for a PR :) ?
