### ISSUE TITLE
Add support for custom TLS Certificate for VEBA

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#366]
**Is your feature request related to a problem? Please describe.**
VEBA currently generates and uses a self-signed TLS certificate for its HTTPS endpoint. For customers who have a need to replace that with a proper CA signed TLS certificate, the process is currently manual as documented [here](https://vmweventbroker.io/kb/advanced-certificates).

**Describe the solution you'd like**
A new optional OVF property that would allow customer to provide the contents of the generated TLS certificate which will be used for VEBA rather than generating a self-signed certificate

**Describe alternatives you've considered**
Manual guidance

**Additional context**
N/A

**Comment by lamw** [comment]
Related #77

**Comment by embano1** [comment]
See #370
