### ISSUE TITLE
Investigate support for importing certificate store for VMware Event Router

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#370]
**Is your feature request related to a problem? Please describe.**
For customers who have an internal Certificate Authority (CA) which is used to issue TLS certificates within their organization, the trusted root CA certificate must be imported to a client system for proper functionality. 

**Describe the solution you'd like**
For this to work with VEBA, the first requirement is to import trusted root CA certicate into the VEBA filesystem and append it to `/etc/pki/tls/certs/ca-bundle.crt` as outlined in this [blog post](http://vcloud-lab.com/entries/vcenter-server/add-a-trusted-root-certificate-to-the-certificate-store-vmware-photon-os)

Once this is performed, you can verify by performing a `curl https://[endpoint]` to the vCenter Server as an example or any other system that had a TLS certificate issue from the same internal CA. It should work without any issues. 

While debugging this with a customer, we found that although VEBA from an OS standpoint can successfully trust the endpoint, the VMware Event Router is not exposed to the underlying certificate store, which prevents this solution from being complete. This may require some investigation within Go on how to best support this feature. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by embano1** [comment]
We can define custom certificates in `govmomi` for the SOAP roundtrips if required (in addition to the container image certs in `/etc/ssl/`. This would require an additional section in the router configuration to indicate where to find additional certificates, e.g. 

```yaml
certificates:
  - "/etc/ssl/certs/ca-certificates.crt" # Root CAs from Ubuntu image
  - "/etc/vmware-event-router/ssl/ca-cert.pem" # custom
```

This would be an optional section. The default behavior (section empty/unspecified) would be as is (i.e. use `"/etc/ssl/certs/ca-certificates.crt"`). 

See here for a simple experiment: https://gist.github.com/embano1/96b78a77c37c33226a6df7442bf23788

**Comment by lamw** [comment]
Per offline discussion - 

1) We'll add support for trusting custom Root CA from VMware Event Router, but this will be a post-deployment process using manual guidance for now. 

2) We'll have some documentation that'll go through the required changes post-VEBA appliance deploy to support this use case and we can re-evaluate having this OOTB based on feedback from end users
