### ISSUE TITLE
Support at-least-once delivery semantics

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#38]
We don't have a good story around at-least-once event delivery (at most once right now). There's different actions we need to take to improve the code to support this, e.g.:

- Checkpointing and replaying vCenter events (if they're still available, downtime may not be > how long vC stores the events), related [issue](https://github.com/vmware/govmomi/issues/1725) in govmomi
- Retries in `Processor.Process`
- Queuing, buffering, batching, dealing with throttling and individual batch item failures (when batching)
- Ordered delivery

**Comment by embano1** [comment]
One approach would be to use a simple version of the ["outbox pattern"](http://www.kamilgrzybek.com/design/the-outbox-pattern/). `stream` events would be put in a  lightweight database such as [sqlite](https://www.sqlite.org/index.html) running next to the connector/or shared between multiple connectors (each having their own table) via `StatefulSet` in Kubernetes. From their on `processors` work against the respective event table and invoke the downstream sink.

Since we use a SQL database we have the following properties:

- ACID properties, such atomic transactions (not between database and downstream of course, but this is fine since we have at-least-once semantics)
- ordered processing
- transaction isolation (which would allow multiple in-process workers but requires some more work on ordered processing, e.g. by a specific `eventKey` or `eventType`, see how [Kinesis](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-parallelization-factor-for-kinesis-and-dynamodb-event-sources/) does it).
- counters to store invocation metadata such as number of attempts, retries, success (bool), etc. to protect from poison messages
- "DLQ" support, e.g. separate DLQ table where we put failed/malformed events
- advanced techniques such as tracking (multiple) `processor` progress, event deduplication, etc. are possible via SQL and ACID properties

cc/ @martindekov

**Comment by embano1** [comment]
Capturing some feedback received and alternatives.
Objections to having state in the appliance to support at-least-once:

- Complexity increases (dealing with state)
- Impact on lifecycle management, e.g. backups, (rolling) upgrades, etc.
- Keeping up with and persisting event streams from large vCenter deployments

While these are very valid concerns, supporting at-least-once semantics require state to track offsets, handle retries, decoupling from upstream/downstream, etc. 

Potential solutions with PROs/CONs:

- **External datastore, e.g. Kafka**
  - PROs: proven event-streaming platform
  - CONs: complexity, out of band and additional requirement to run the vCenter Event Broker appliance
- **BoltDB**
  - PROs: lightweight, simple forms of transactions
  - CONs: original project archived (fork from CoreOS team available), trim/truncate seems to be not available, no replication/HA support (scale out), potential concurrency (r/w locking) performance concerns (to be tested)
- **sqlite**
  - PROs: lightweight and feature-rich embedded SQL store (incl. watches)
  - CONs: cgo dependency, no replication/HA support (scale out)
- **RDBMS**
  - PROs: full SQL/ACID semantics incl. watches and complex queries, active-active/passive deployments
  - CONs: additional (larger) dependency with state in the appliance and associated lifecycle concerns
- **etcd**
  - PROs: lower resource footprint than RDMBS, available already in the appliance as backend for Kubernetes cluster, replication (active-passive), watches, distributed systems and concurrency primitives, incl. some form of transactions, pure Go implementation and bindings
  - CONs: directly leveraging the Kubernetes state store might be seen as an anti-pattern and can cause cluster issues with too much traffic (no QoS)

**Comment by martindekov** [comment]
Hey Michael on the call I remember someone mentioning reusing the database containing the Events from the vCenter so there is no data duplication. (vCenter DB and VEBA DB essentially having duplicate event objects)

Cant we just mount folder from VM's file system onto the connector's container and save the Event's IDs as files on the appliance's file system, maybe some very simple additional information? Do we need whole DB, can't we just keep very simplistic data in a files? What were the arguments against the approach?
