### ISSUE TITLE
Configure log rotation for K8s + Container/Pod Logs

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#381]
**Is your feature request related to a problem? Please describe.**
Configure log rotation for K8s + Container/Pod Logs

`/etc/logrotate.d/allvarlogs`
```
/var/log/*.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 25M
    daily
    dateext
    dateformat -%Y%m%d-%s
    create 0644 root root
}
```

`/etc/logrotate.d/allpodlogs`
```
/var/lib/docker/containers/*/*.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 5M
    daily
    dateext
    dateformat -%Y%m%d-%s
    create 0644 root root
}
```

Reference: https://vividcode.io/enable-log-rotation-in-kubernetes-cluster/

**Comment by embano1** [comment]
`/var/log/pods/*/*.log` -> so (Docker) container logs are not under `/var/lib`?

**Comment by lamw** [comment]
Per offline discussion - 

It looks like kubeadm is still using Docker versus Containerd as the runtime. Instead of having to setup logrotate configuration, we can do this in Docker by adding the [desired logging options](
https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver) into `/etc/docker/daemon.json` 

e.g.
```console
cat /etc/docker/daemon.json
{
    "bip": "172.26.0.1/16",
    "log-opts": {
       "max-size": "10m",
       "max-file": "5"
    }
}
```
