### ISSUE TITLE
Change default PID network to prevent collisions

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#39]
User issue reported:

```
network 10.32.0.0/12 overlaps with existing route 10.47.159.0/24 on host
```

Potential workaround: https://github.com/weaveworks/weave/issues/2736#issuecomment-453083678

PR and test with `10.99.0.0/20` also update limits (number of functions), architecture and FAQ docs on this setting. Make it advanced setting in OVF (end of deployment options setting)?

cc/ @kremerpatrick

**Comment by kremerpatrick** [comment]
I don't have a full grasp on what 10.32.0.0/12 is used for, but it's a private network on the VEBA that cannot overlap with the IP address assigned to the appliance? So we're talking about potentially an advanced setting with a default of 10.32.0.0/12 and a warning at the IP Address input field of the potential overlap problem? And then documentation guidance on how to select a subnet / what the impact of the subnet size is?

**Comment by lamw** [comment]
This network is used to provide IPs to all the PODs running. There's a system default which is defined by Weave (which is the network stack that's being used). If you look at the Issue linked, the developers attempted to pick a network that mostly works OOTB, but in your case, there's a conflict. I was surprised to see the network range to be so large and suspect its probably design for larger deployments. For VEBA, having a smaller <4K IPs should be more than enough (at least for the default). 

The proposed change will also introduced an Advanced setting that in case another conflict occurs, end users can simply picking another network and guidance is probably going to be /20 as well. Hope this makes sense and again, it's mostly internal/transparent but you happen to be the lucky one hitting the overlap.
