### ISSUE TITLE
Create a base Knative PowerShell and PowerCLI Container Image

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#416]
**Describe the solution you'd like**
A generic Knative PowerShell and PowerCLI Container that can be used as a base image for other related Knative PS/PCLI container images. This allows us to maintain a single image that contains all the required packages/libraries to support core PowerShell and PowerCLI functionality without having to rebuild every function when library dependency or version changes

**Comment by embano1** [comment]
@lamw close?
