### ISSUE TITLE
Set concurrency to 1 for PS template based images

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#447]
**Is your feature request related to a problem? Please describe.**
Currently the http listener in PS-based images (incl. PCLI) are written in a sync (blocking) way. This could lead to issues where concurrent requests are not processed in a timely manner, leading to latency issues or timeouts.

**Describe the solution you'd like**
Set (hard) concurrency limit to "1" in Knative service definition for each container so the Knative autoscaler can perform more informed scaling decisions.

Details: https://knative.dev/docs/serving/autoscaling/concurrency/

**Describe alternatives you've considered**
Write http context handler in non-blocking (async) fashion.

**Additional context**
Future optimizations could be async code, setting concurrency is a short-term fix.

**Comment by lamw** [comment]
Is this going to be an issue when deploying PS/PCLI-based functions using the VEBA UI, since we don't allow setting the concurrency limit there?

**Comment by embano1** [comment]
> Is this going to be an issue when deploying PS/PCLI-based functions using the VEBA UI, since we don't allow setting the concurrency limit there?

Good point! We could implicitly enforce it (might not be desired by user) or add an option in the UI to set fields like concurrency and min/max scale.

**Comment by embano1** [comment]
Looks like without setting a concurrency limit we currently have a bug in all containers using the PS base template (listener). Invoking the http server with two (or more) concurrent requests will yield only one request being executed while the other requests will see `200` but their requests are actually never processed.

Tested with:

```powershell
Function Process-Handler {
   param(
      [Parameter(Position = 0, Mandatory = $true)][CloudNative.CloudEvents.CloudEvent]$CloudEvent
   )
   
   Write-Host "$(Get-Date) - Processing incoming request"
   $delay = 5s
   Start-Sleep -s $delay
   Write-Host "$(Get-Date) - Processing done"
}
```

**Comment by embano1** [comment]
Update: might be related to how threading is implemented with blocking `GetContext()` in the listener and using sleep which pauses the thread. Even if `sleep()` might not be recommended, it shows issues with threading in our current server implementation potentially dropping events.

**Comment by lamw** [comment]
Related to #459
