### ISSUE TITLE
Issue With ce-ps-base:1.1 ?

### ISSUE THREAD

**Issue by darrylcauldwell** [vmware-samples/vcenter-event-broker-appliance#456]
**Describe the bug**
A clear and concise description of what the bug is:

I am trying to create a new function from the new base Powershell image but this fails when starting HTTP listener.

**To Reproduce**
Steps to reproduce the behaviour:

The simplest way to simulate this is by creating a new image from the base with an empty handler.ps1 and start locally like:

cat <<EOF > Dockerfile
FROM projects.registry.vmware.com/veba/ce-ps-base:1.1
ENV TERM linux
ENV PORT 8080
COPY handler.ps1 handler.ps1
CMD ["pwsh","./server.ps1"]
EOF

touch handler.ps1

docker build -t is-ce-base-broken:1.0  .

<img width="1179" alt="is-image-broken" src="https://user-images.githubusercontent.com/5120008/123100542-1f600200-d42b-11eb-8a8e-316714aec414.png">
06/23/2021 12:11:33 - PowerShell HTTP server start listening on 'http://*:8080/'
Write-Error: 06/23/2021 12:11:33 - Init Processing Error: System.Management.Automation.CommandNotFoundException: The term 'Process-Init' is not recognized as a name of a cmdlet, function, script file, or executable program.

**Expected behaviour**
A clear and concise description of what you expected to happen:

When starting image locally I would expect the HTTP listener to initialise like:

docker run -it projects.registry.vmware.com/veba/kn-ps-echo:1.1     
06/23/2021 12:52:31 - PowerShell HTTP server start listening on 'http://*:8080/'
06/23/2021 12:52:31 - Processing Init
06/23/2021 12:52:31 - Init Processing Completed

**Screenshots**

**Version (please complete the following information):**
 - VEBA Form Factor: [e.g. Appliance or K8s]
          Appliance
 - VEBA Version: [e.g. v0.4.0]
          0.6.1

**Additional context**

**Comment by embano1** [comment]
@darrylcauldwell Thx for reaching out! Can you please provide your handler via inline-code markdown here? I'm guessing you're missing two functions in there.

**Comment by darrylcauldwell** [comment]
The handler.ps1 (and Dockerfile) I was using the old image which looking to move to build from new image:

curl -O https://raw.githubusercontent.com/darrylcauldwell/veba-knative-mm-exit/master/Dockerfile
curl -O https://raw.githubusercontent.com/darrylcauldwell/veba-knative-mm-exit/master/handler.ps1

**Comment by darrylcauldwell** [comment]
Your reply mentioned two missing functions,  after checking other examples it looks like Process-Init and Process-Shutdown are now needed in addition to Process-Handler.

**Comment by embano1** [comment]
Yes, correct we slightly adjusted the handler template to provide more flexibility around init/shutdown. See this [post](https://williamlam.com/2021/06/vmware-event-broker-appliance-veba-v0-6-1.html) for details.

**Comment by darrylcauldwell** [comment]
Great thank you.  Initial signs are good that this has resolved issue.
