### ISSUE TITLE
Add a release timeline (shortcode) to the VEBA website

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#483]
**Describe the solution you'd like**
It would be great to have a timeline feature on the VEBA website implemented, which highlight e.g. **dates**, **releases** as well as the shipped **updates** which were introduced with such.

Example from my current VMUG slides:

![veba_release_timeline](https://user-images.githubusercontent.com/31652019/125334977-46d02d80-e34c-11eb-99c8-43115124ce92.jpg)

Example `shortcode`: [Hugo Timeline Shortcode - MetalBlueberry](https://metalblueberry.github.io/post/howto/2021-02-28_hugo_timeline_shortcode/).

Another great example of such an implementation is available on @pksrc blog [HERE](https://cloudtekki.com/post/looking-back-at-2020/) <-- .

**Comment by lamw** [comment]
@pksrc Any progress on adding this to docs?

**Comment by pksrc** [comment]
Working on this today, should have it in today or tomorrow
