### ISSUE TITLE
Add missing endpoint urls to DCUI

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#490]
**Is your feature request related to a problem? Please describe.**
The endpoint URL's `/events` and `/top` needs to be added to the VEBA DCUI screen.

![image](https://user-images.githubusercontent.com/31652019/126599804-d8d39f84-b04f-4bf0-97b2-7d068f2e24c1.png)

**Comment by lamw** [comment]
Depending on the chosen Event Provider(s) AND Event Processor during deployment, there will be various combinations of endpoint URLs that will be valid and displayed. Given we will have additional providers and/or remove processors, I want to see if we can provide a method to `dcui` application to simply get a list of the endpoints to render to the screen. 

I was thinking that setup scripts, could create a `veba-endpoints` file that is then read by DCUI which should contain the label and URL path, which it can then dynamically construct the full URL 

```console
cat veba-endpoints

Appliance Status,  /status
Install Logs, /bootstrap
Appliance Statiastics, /stats
```

There will be a set of default endpoints, but others will be appended to the file depending on the customer configuration and I think this could work and decouple DCUI from having to have any of this logic and makes it easier to change/update in future

Here's dump of all the endpoints we currently have:

* /status - Appliance Status 
* /bootstrap - Installation Logs
* /stats/[provider] - Multiple Metrics endpoint
* /webhook - Webhook Provider
* /top - cAdvisor
* /events - Sockeye for viewing Events (only applicable for Knative)

**Comment by codegold79** [comment]
I like the idea of decoupling the DCUI binary from the list of endpoints. So, given the example `veba-endpoints` file @lamw provided, DCUI will list out in the bottom half the screen the following where `<domain>` will be determined by the DCUI app and will be something like `veba-kn.jarvis.lab`:

```
Appliance Status: https://<domain>/status
Install Logs: https://<domain>/bootstrap
Appliance Statistics: https://<domain>/stats
```

DCUI will not add any other endpoints except what is in the `veba-endpoints` file.

**Comment by lamw** [comment]
For readability, I'd like to propose an addition entry in `veba-endpoints` file which will determine the header of a given section. Expected format for the file will now contain 3 items per row: `header`, `Description`, `endpoint`

Here's a real example:

```console
cat /etc/veba-endpoints

Appliance Configuration, Status, /status
Appliance Configuration, Install Logs, /bootstrap
Appliance Configuration, Resource Utilization, /top
Appliance Configuration, Events, /events
Appliance Configuration, Webhook, /webhook
Appliance Provider Stats, vCenter, /stats/vcenter
Appliance Provider Stats, Webhook, /stats/webhook
```

which should then be rendered by DCUI like the following:


```console
Appliance Configuration:

Status: https://<domain>/status
Install Logs: https://<domain>/bootstrap
Resource Utilization: https://<domain>/top
Events: https://<domain>/events
Webhook: https://<domain>/webhook

Appliance Provider Statistics:

vCenter: https://<domain>/stats/vcenter
Webhook: https://<domain>/stats/webhook
```

Lastly, DCUI application can expect to find the file located in `/etc/veba-endpoints`

**Comment by embano1** [comment]
Since this will be machine-rendered for DCUI, should input be structured (ie JSON, TOML) or text-friendly (comma-separated)? The latter might be harder to parse and unlikely someone is going to directly read that file IMHO.

**Comment by lamw** [comment]
> Since this will be machine-rendered for DCUI, should input be structured (ie YAML,JSON, TOML) or text-friendly (comma-separated)? The latter might be harder to parse and unlikely someone is going to directly read that file IMHO.

The input file is comma-separated:

```console
Appliance Configuration, Status, /status
Appliance Configuration, Install Logs, /bootstrap
Appliance Configuration, Resource Utilization, /top
Appliance Configuration, Events, /events
Appliance Configuration, Webhook, /webhook
Appliance Provider Stats, vCenter, /stats/vcenter
Appliance Provider Stats, Webhook, /stats/webhook
```

**Comment by embano1** [comment]
Ok, so we have to also trim any tab/whitespace (not sure if we already do this)

**Comment by codegold79** [comment]
> Ok, so we have to also trim any tab/whitespace (not sure if we already do this)

@embano1, when you say "we" do you mean DCUI should trim whitespace or do you mean I can keep any leading/following whitespace and assume they were intended (perhaps for padding)? Or when you say "we" do you mean William should make sure that the `veba-endpoints` comma separated values are trimmed of whitespace?

**Comment by lamw** [comment]
> > Ok, so we have to also trim any tab/whitespace (not sure if we already do this)
> 
> @embano1, when you say "we" do you mean DCUI should trim whitespace or do you mean I can keep any leading/following whitespace and assume they were intended (perhaps for padding)? Or when you say "we" do you mean William should make sure that the `veba-endpoints` comma separated values are trimmed of whitespace?

I believe he was referring to the DCUI application. I'll ensure there's no leading/trailing whitespace (already updated the reference sample) and hopefully DCUI can handle in case there's a need for it but don't see one now but might be good from a defensive point of view to ensure app doesn't magically crash if it can't process

**Comment by codegold79** [comment]
> but might be good from a defensive point of view

I can also allow whitespace so that you can change the padding if you'd like. I don't think whitespace will make anything crash. I'm just printing text on a screen. But I can also trim leading and following whitespace really easily.

**Comment by embano1** [comment]
> > but might be good from a defensive point of view
> 
> 
> 
> I can also allow whitespace so that you can change the padding if you'd like. I don't think whitespace will make anything crash. I'm just printing text on a screen. But I can also trim leading and following whitespace really easily.

Yeah, trimming was my concern/proposal if needed so things line up nicely. Looks like you found consensus on how to move forward 👍

**Comment by codegold79** [comment]
I've provided @lamw with the new DCUI binary. He said he'll push it up in a PR. 

Let me know if I can be of further help.
