### ISSUE TITLE
[BUG] Broken documentation link

### ISSUE THREAD

**Issue by Kyleset** [vmware-samples/vcenter-event-broker-appliance#491]
Broken link on this page: https://vmweventbroker.io/kb/contribute-functions

![image](https://user-images.githubusercontent.com/7346172/126681759-88e10d85-69c3-46db-8f1e-0afffdec70d2.png)

That link points to: https://github.com/openfaas-incubator/kafka-connector

Which doesn't exist anymore.

**Comment by lamw** [comment]
Thanks for reporting @Kyleset 

We also need to update that page to reflect Knative function development. For now, you can refer to https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/examples/knative for examples but the guidance on that page should still mostly be applicable
