### ISSUE TITLE
[BUG] Python "print" function requires parentheses during variable escapes

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#498]
**Describe the bug**

While evaluating Photon OS 4.0, it looks like version of Python is now 3.x which requires all function calls to be wrapped in parentheses. This affects any of the shell scripts which escapes the variables like https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/development/files/setup-06-event-processor.sh#L17

```
echo -n ${VCENTER_SERVER} | python -c 'import sys,json;data=sys.stdin.read(); print json.dumps(data)[1:-1]'
  File "<string>", line 1
    import sys,json;data=sys.stdin.read(); print json.dumps(data)[1:-1]
                                                 ^
SyntaxError: invalid syntax
```

Fix is simple, just use`print(json.dumps(data)[1:-1])`

**Comment by embano1** [comment]
QQ: shall we use jq (and it's related tostring helper) to get rid of this python code? Also, are all of these VARs only used in ytt or also scripts? If only ytt we could shift the work towards ytt and avoid the parsing all together here?

**Comment by lamw** [comment]
Do you have an example jq command in mind? The reason is that the source isn't JSON as its parsed through shell script as these are coming from OVF properties. We then need to ensure they're properly escaped prior to constructing the `veba-config.json` file which is then used by ytt (in the other YTT PR)

No, these variables are also used in a few other places when setting up the required secrets, so its not YTT exclusively

**Comment by embano1** [comment]
Yes, IIRC we introduced the Python one-liner for exactly that fact to avoid parsing bugs due to incorrectly (or not) escaped input strings.

> Do you have an example jq command in mind? 

```console
# input
echo -n $USER
corp\administrator%

echo -n $USER | jq -Rs | xargs
corp\\administrator

# input
echo -n $PASSWORD
p@$$w0rd!%

echo -n $PASSWORD | jq -Rs | xargs
p@$$w0rd!

# example with more complex text to JSON
echo $TEXT
He said "jq is the way to go"

echo $TEXT | jq -Rs
"He said \"jq is the way to go\"\n"

# error due to "
echo $TEXT | jq -Rs | xargs
xargs: unterminated quote
```

`xargs` is required here because you want to strip the opening/closing `"` (instead of using `tr` to remove any `"`). The only reason you want to strip `"` is because you're using some output in concatenated strings, e.g. vCenter address. Otherwise you could easily keep the quotes around the JSON-escaped strings (and not having to use `xargs` at all).

**Comment by lamw** [comment]
There looks to be a [bug or "feature"](https://github.com/stedolan/jq/issues/1110) in jq which prevents the use of `$(echo -n ${USER} | jq -Rs)`

Workaround that I've found is to use `$(eval echo -n ${USER} | jq -Rs)`

The next issue is getting output stored in variable, which was mentioned [here](https://stackoverflow.com/questions/48090023/cant-store-output-of-jq-in-variable) that the use of explicit "dot" for jq is needed.

Final solution: `VAR=$(eval echo -n ${USER} | jq -Rs)`

Applying this workaround in appliance build to see if there's any other unexpected behaviors or issues
