### ISSUE TITLE
Update VEBA Architecture Diagram

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#535]
**Is your feature request related to a problem? Please describe.**
https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/development/docs/kb/img/veba-architecture.png needs to be updated to include additional Event Providers(s), Endpoints and Deprecated Event Processors

**Comment by embano1** [comment]
In terms of deprecation, I think that should not go into the architecture slide (yet) since the deprecation is only affected in the appliance deployment mode (not router). WDYT?
