### ISSUE TITLE
[BUG] Can't find powercli template

### ISSUE THREAD

**Issue by it-podshivalov** [vmware-samples/vcenter-event-broker-appliance#541]
Hello!
I want to run some of powercli example functions.
When I execute `faas-cli template pull` I get 13 templates in my template folder, but there is no powercli here.
And I can't move on.
Help me please.

![изображение](https://user-images.githubusercontent.com/57752592/128059180-78455501-1dde-4c64-9be5-7fe82b5aadbe.png)

**Comment by lamw** [comment]
Hi @it-podshivalov 

We had transition away from OpenFaaS to Knative-based Functions a couple of releases ago and all updated function examples can be found at https://vmweventbroker.io/examples-knative

Each function example (which is linked in the Github Repo) will contain a README and how to deploy/etc.

**Comment by it-podshivalov** [comment]
Hi William! Thank you for aswer.

I will re-lay installation with a Knative-based Functions.
