### ISSUE TITLE
Add supervisord to important containers

### ISSUE THREAD

**Issue by dvolozhinok** [vmware-samples/vcenter-event-broker-appliance#547]
**Is your feature request related to a problem? Please describe.**
We use VEBA to send events to the customer about the migration of his VM to Telegram chat using Telegram bot previously created with Botfather. But sometimes the system stops working normally.
We have already encountered three times that there are no messages in Telegram chat for the current day (sure it's problem with VEBA because there plenty migration per day for these VMs, about 50 migrations per day). This means that there was some kind of failure in VEBA. Twice we couldn't find any logs that can which could explain this behavior. And on the third time there was a problem with pods rules. But we had lack of time so didn't collect any logs.

Most likely, the first 2 cases were caused by a violation of the operation of the service inside the container. Please implement supervisord in critically important containers to exclude the scenario when the service crashes inside the container.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Nothing at the moment.

**Comment by dvolozhinok** [comment]
Link to supervisord: http://supervisord.org
I have worked with another system which already have supervisord implemented in critically important containers. It surely helps to automatically restart service or services inside containter in case of service failure.

**Comment by embano1** [comment]
Thx for reporting this issue and your nice use case! Before we introduce another dependency, which must be carefully evaluated, we would love to troubleshoot this issue further. K8s already acts as a supervisor for pods and containers, so we'd like to better understand whether there's an issue with the appliance or application logic. 

Btw: The next release will include a couple of operational features, eg sending logs to an external server.

**Comment by lamw** [comment]
@dvolozhinok First off, great use case! I hadn't heard of folks wanting to receiving migration activities via Telegram (not used myself), was this mainly to get real time updates via that channel? 

Secondly, As Michael mentioned, we definitely would like to better understand the issue that you were observing as there could be number of things that may have resulted in what you saw. From too many events over-running the router, resources, eviction due to resource pressure, etc. It is also not clear what Event Processor (Knative, EventBridge, OpenFaaS) you're using and a bit more details about your function would be helpful.

**Comment by dvolozhinok** [comment]
@lamw We are using Knative.
Please ask questions that will help you understand the problem.
Or we can wait for the next version, when it will be possible to collect logs to an external system and send you logs when the situation repeats again.

**Comment by lamw** [comment]
Lets combine this ask with the other Issues you raised. Please send us an email and we can find a time that works to discuss your requirements. We also will have an early Tech Preview for the upcoming release, if you're interested, we can provide you an early build which has the external syslog feature
