### ISSUE TITLE
Update all PowerShell/PowerCLI images w/server.ps1 fixes

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#549]
**Is your feature request related to a problem? Please describe.**
Incorporate fixes #494 and #542 from `server.ps1` into PowerShell/PowerCLI base images and all examples that reference these base images. 

The new container tag will be `1.2`

**Comment by embano1** [comment]
Please hold until we resolve the SDK issue: https://github.com/cloudevents/sdk-powershell/issues/42

**Comment by lamw** [comment]
Roger. I didn't realize we still had another dependency

**Comment by embano1** [comment]
TODO

- [ ] Update server code
- [ ] Bump PS CE SDK version

**Comment by embano1** [comment]
@lamw PS CE SDK has a new release containing a critical fix https://github.com/cloudevents/sdk-powershell/releases/tag/v0.3.1
