### ISSUE TITLE
[BUG] kn-pcli-fn needs a check to ensure vCenter connection is still open

### ISSUE THREAD

**Issue by kremerpatrick** [vmware-samples/vcenter-event-broker-appliance#557]
**Describe the bug**
The connection vCenter can time out, resulting in a failed function invocation. 

**To Reproduce**

There are numerous conditions that can a cause a vCenter disconnect. It should be handled in a try/catch.

**Expected behavior**
Check the connection and reconnect as necessary.

**Screenshots**

**Version (please complete the following information):**
 - VEBA Form Factor: [e.g. Appliance or K8s]
 - VEBA Version: [e.g. v0.6.1]

**Additional context**

**Comment by embano1** [comment]
Closing as per PR discussion
