### ISSUE TITLE
Update websites welcome page to include new v0.7 features and enhancements 

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#561]
**Is your feature request related to a problem? Please describe.**
It's necessary to renovate the welcome page to e.g. reflect the upcoming features and enhancements.

- [x] Highlight new Horizon Provider
- [x] Highlight Generic Webhook support
- [x] Update *Featured Functions* section

**Comment by rguske** [comment]
@pksrc @lamw @embano1 
Changes are made to the section header based on what we've discussed on Friday. Please comment.

![image](https://user-images.githubusercontent.com/31652019/132219067-37638dca-9927-487b-9521-2078723619f0.png)

**Comment by rguske** [comment]
Changes to the *Featured Functions* section:

![image](https://user-images.githubusercontent.com/31652019/132225305-57a156c3-7422-4ef2-8624-1e3e608e3026.png)

Please comment.

**Comment by embano1** [comment]
> Changes are made to the section header based on what we've discussed on Friday. Please comment.

We could slightly change the remediation box to actually talk about remediation scenarios instead of "imagining new possibilities". E.g. "Automatically revert or fix system issues based on state changes".

**Comment by embano1** [comment]
> Changes to the Featured Functions section:

Alarm function: "vSphere alarm events do not provide metadata about defined triggers and thresholds. This example demonstrates how Knative flows can be used to enrich events and send it to other functions for consumption".

Slack notification: "...will send a message to Slack with details about the virtual machine, e.g. when and by whom was this event triggered." (avoid CAPS)
