### ISSUE TITLE
event does not have UUID

### ISSUE THREAD

**Issue by sameermahajan** [vmware-samples/vcenter-event-broker-appliance#565]
**Is your feature request related to a problem? Please describe.**
Currently event  does not have UUID field  for objects (e.g. VM) in it.

**Describe the solution you'd like**
I would like to have UUID field for objects in it.

**Describe alternatives you've considered**
Alternatives that I have considered is to go back to vCenter after receiving an event, query it  for UUID and enrich the event with UUID.

**Additional context**
For vm power off the  event that is currently received is:

  specversion: 1.0
  type: com.vmware.event.router/event
  source: https://127.0.0.1:8989/sdk
  subject: VmPoweredOffEvent
  id: 8871329a-048a-41de-a1ab-bd282a5ed6d3
  time: 2021-09-01T05:52:43.212561671Z
  datacontenttype: application/json
Extensions,
  vsphereapiversion: 7.0.2.0
Data,
  {
    "Key": 29,
    "ChainId": 29,
    "CreatedTime": "2021-09-01T05:52:43.212561671Z",
    "UserName": "user",
    "Datacenter": {
      "Name": "SDDC-Datacenter",
      "Datacenter": {
        "Type": "Datacenter",
        "Value": "datacenter-3"
      }
    },
    "ComputeResource": {
      "Name": "Cluster-1",
      "ComputeResource": {
        "Type": "ClusterComputeResource",
        "Value": "domain-c8"
      }
    },
    "Host": {
      "Name": "10.2.32.4",
      "Host": {
        "Type": "HostSystem",
        "Value": "host-16"
      }
    },
    "Vm": {
      "Name": "tkg-cluster-01-md-0-67b69c558f-bdb4j",
      "Vm": {
        "Type": "VirtualMachine",
        "Value": "vm-1099"
      }
    },
    "Ds": null,
    "Net": null,
    "Dvs": null,
    "FullFormattedMessage": "{vm.name} on  {host.name} in {datacenter.name} is powered off",
    "ChangeTag": "",
    "Template": false
  }

which doesn't have UUID in it.

**Comment by embano1** [comment]
Closing as dup of https://github.com/vmware/govmomi/issues/2560
