### ISSUE TITLE
[BUG] event.FullFormattedMessage prints the format itself rather than correct message

### ISSUE THREAD

**Issue by sameermahajan** [vmware-samples/vcenter-event-broker-appliance#566]
**Describe the bug**
When FullFormattedMessage from event is printed it prints the format (e.g. {vm.name} on {host.name} in {datacenter.name} is stopping) rather than something like

foo on bar in blah is stopping

**To Reproduce**
1. start veba router pointing it to a vcenter
2. power off a VM / fire vm  power off event (in case of simulator)
3. observe the event coming out to be something like:
  specversion: 1.0
  type: com.vmware.event.router/event
  source: https://127.0.0.1:8989/sdk
  subject: VmPoweredOffEvent
  id: 8871329a-048a-41de-a1ab-bd282a5ed6d3
  time: 2021-09-01T05:52:43.212561671Z
  datacontenttype: application/json
Extensions,
  vsphereapiversion: 7.0.2.0
Data,
  {
    "Key": 29,
    "ChainId": 29,
    "CreatedTime": "2021-09-01T05:52:43.212561671Z",
    "UserName": "user",
    "Datacenter": {
      "Name": "SDDC-Datacenter",
      "Datacenter": {
        "Type": "Datacenter",
        "Value": "datacenter-3"
      }
    },
    "ComputeResource": {
      "Name": "Cluster-1",
      "ComputeResource": {
        "Type": "ClusterComputeResource",
        "Value": "domain-c8"
      }
    },
    "Host": {
      "Name": "10.2.32.4",
      "Host": {
        "Type": "HostSystem",
        "Value": "host-16"
      }
    },
    "Vm": {
      "Name": "tkg-cluster-01-md-0-67b69c558f-bdb4j",
      "Vm": {
        "Type": "VirtualMachine",
        "Value": "vm-1099"
      }
    },
    "Ds": null,
    "Net": null,
    "Dvs": null,
    "FullFormattedMessage": "{vm.name} on  {host.name} in {datacenter.name} is powered off",
    "ChangeTag": "",
    "Template": false
  }

**Expected behavior**
Notice:

"FullFormattedMessage": "{vm.name} on  {host.name} in {datacenter.name} is powered off",

it should have been something like:

"FullFormattedMessage": "vm-1099 on  host-16 in SDDC-Datacenter is powered off",

**Screenshots**
Please refer to the event coming through given  above.

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: v0.6.1

**Additional context**
FullFormattedMessage property of event  should give formatted message which rather seems to be coming out format like.

**Comment by embano1** [comment]
Closing as dup of: https://github.com/vmware/govmomi/issues/2559
