### ISSUE TITLE
Duplicate env parsing in tagging example

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#570]
Dupe code:

https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/192e1d017c713f43eeed035b53159ea41807a9c7/examples/knative/powercli/kn-pcli-tag/handler.ps1#L57-L59

**Comment by lamw** [comment]
This is needed because in the `Process-Init`, it only extracts out the vCenter credentials but in `Process-Handler`, this is where it extract the Tag name

**Comment by embano1** [comment]
Ah, ok...to avoid global state. Just note that the exception message is incorrect in both places (wrong env name)
