### ISSUE TITLE
K8s Loadbalancer issue

### ISSUE THREAD

**Issue by nguyendk270996** [vmware-samples/vcenter-event-broker-appliance#574]
I recently deploy VEBA into our vCenter. Despite the deploy said done (Have the console screen show me urls, kubectl get pods -all-namespaces show everything is Running) but services envoy (LoadBalancer) is pending for External IP.

![ảnh](https://user-images.githubusercontent.com/89342352/132381295-c781564a-ec76-4a07-a16b-0e646054b9dc.png)

This showing everything is running 

![ảnh](https://user-images.githubusercontent.com/89342352/132381388-0daadce7-f53b-4013-937d-a1c0525fdd0c.png)

However the LoadBalancer is pending for IP therefore I can't not access though web interfaces. 

This happened on both Stagging in my company system and my Homelab environments.

**Comment by embano1** [comment]
@nguyendk270996 which version of the appliance are you running?

**Comment by nguyendk270996** [comment]
@embano1 I'm using v0.6.1

**Comment by embano1** [comment]
Alright, I just looked at this with @rguske and we can confirm that the default is `LoadBalancer`. However, this does not influence the behavior of the appliance, ie. you should be able to access all endpoints, e.g. `.../bootstrap`, etc.

Can you please confirm?

**Comment by nguyendk270996** [comment]
@embano1  can you specific 1 endpoint and port so I can do the check for you really quick 😄

**Comment by embano1** [comment]
Yup, use the FQDN you defined during the deployment and then it's `https://<FQDN>/status`

**Comment by nguyendk270996** [comment]
yes I can access using the FQDN/status.

**Comment by embano1** [comment]
Perfect, can this issue be closed then?

**Comment by nguyendk270996** [comment]
Yes, thanks you sir. Have a nice day @embano1
