### ISSUE TITLE
[BUG] server.ps1 no longer handles ctrl+c and runs Process-Shutdown

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#615]
**Describe the bug**
I noticed during local development testing using the latest `projects.registry.vmware.com/veba/ce-pcli-base:1.3` image which has all latest `sever.ps1` fixes, that it no longer properly runs the `Process-Shutdown` which means it does not disconnect from vCenter Server. 

**To Reproduce**

Output from 1.3 Behavior
```
09/27/2021 13:56:57 - Successfully connected to vcsa.primp-industries.local

09/27/2021 13:56:57 - Init Processing Completed

^C09/27/2021 13:57:17 - PowerShell HTTP Server stop requested. Waiting for server to stop
```

Output from 1.2 Behavior
```
09/27/2021 13:45:34 - Successfully connected to vcsa.primp-industries.local

09/27/2021 13:45:34 - Init Processing Completed

^C09/27/2021 13:47:01 - PowerShell HTTP Server stop requested. Waiting for server to stop
09/27/2021 13:47:01 - Processing Shutdown

09/27/2021 13:47:01 - Disconnecting from vCenter Server

09/27/2021 13:47:01 - Shutdown Processing Completed

09/27/2021 13:47:01 - PowerShell HTTP server stop requested
09/27/2021 13:47:01 - PowerShell HTTP server is stopped
```

**Expected behavior**
Ctrl+C will properly execute `Process-Shutdown` before terminating the PowerShell HTTP server

**Comment by embano1** [comment]
Partially fixed: #614
