### ISSUE TITLE
[BUG] VEBA DCUI fails to parse (pre) release builds

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#634]
**Describe the bug**
It looks like the VEBA DCUI  is expecting `Version` field to contain `vX.Y.Z` and when it sees a pre-release which contains `release-`, and it looks like it fails to parse and does not display further information including VEBA endpoints

As a test, I manually updated the `/etc/veba-release` and removing `release-` string and restarted `getty@tty1.service` service and everything displayed correctly 

```
root@veba [ ~ ]# cat /etc/veba-release
Version: release-0.7.0
Commit: c9890cf
Processor: Knative
Processor: Knative
```

**To Reproduce**
Deploy release build of VEBA

**Expected behavior**
VEBA DCUI properly renders ` /etc/veba-release`

**Screenshots**

<img width="1386" alt="Screen Shot 2021-09-30 at 9 35 25 AM" src="https://user-images.githubusercontent.com/602199/135495571-fde69a03-7cb0-4e88-98e0-b6de8fe24161.png">

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: release-v0.7.0

**Comment by codegold79** [comment]
I'm going to make it so that whatever characters is after the word "Version:" will be what appears as the version. So, one can do anything like,

```text
Version: #$@*!
Commit: c9890cf
Processor: Knative
```

```text
VMware vCenter Event Broker Appliance (VEBA) #$@*!, Commit #c9890cf
```

**Comment by lamw** [comment]
@codegold79 Thanks for the quick fix. Already verified and submitted PR #637
