### ISSUE TITLE
[BUG] Using VI editor throws error

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#635]
**Describe the bug**

When using `vi` editor, the following error is observed:
```
Error detected while processing /etc/vimrc[7]../usr/share/vim/vim82/syntax/syntax.vim:
line   42:
E216: No such group or event: filetypedetect BufRead
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```

**To Reproduce**
Open any file using `vi`

**Expected behavior**
VI opens without issues

**Screenshots**
N/A

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: release-v0.7.0

**Additional context**
N/A

**Comment by lamw** [comment]
Just spoke w/Photon OS team and looks like this issue was just fixed https://github.com/vmware/photon/commit/4a9586a0a1ecd8875f137d5f97b54ec7883f5fd0 and new VIM RPMs will be available shortly

**Comment by embano1** [comment]
So we need to hold the release?

**Comment by lamw** [comment]
No, the PhotonOS team has just fixed the problem and was waiting for RPM to get published on their repo. Just got confirmation through another VEBA appliance build and we're good, no changes needed on our end.
