### ISSUE TITLE
Add Prometheus support

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#657]

**Comment by dk-d-n** [comment]
Any particular reason this was never rolled into any of the recent releases @embano1?

**Comment by embano1** [comment]
@dk-d-n yes, there's two reasons:

1) The person who wanted to work on this is not able to work on this anymore
2) As part of a major `v0.8` release we are planning to migrate to the full Knative backend, including event sources for vSphere and Horizon. Note that Knative today already gives us a lot of telemetry (for Prometheus), so you are already able to use it. We just want to add more event sources to replace the `router` and have end-to-end metrics support.
