### ISSUE TITLE
Enable customization of Docker networks

### ISSUE THREAD

**Issue by virtualhobbit** [vmware-samples/vcenter-event-broker-appliance#74]
Please can we enable the customization of the Docker network?

Currently, anyone of 172.17.0.0/16 is unable to deploy the appliance.

Due to the popularity of this CIDR block I imagine the prevents a number of customers from trying out this fling.

**Comment by lamw** [comment]
Thanks for the feedback Mark. This has been the first request we've had regarding the default bridged network for Docker. We did run into a similar issue w/Pod CIDR that could conflict with an existing network. I think it makes sense to support customizing this just like we do with Pod CIDR as an "Advanced Option".

Leaving https://success.docker.com/article/how-do-i-configure-the-default-bridge-docker0-network-for-docker-engine-to-a-different-subnet as a note

**Comment by virtualhobbit** [comment]
Thanks, William.

Let me know if you'd like me to guinea pig anything :-)

**Comment by lamw** [comment]
Here's Beta build of VEBA https://download3.vmware.com/software/vmw-tools/veba/vCenter_Event_Broker_Appliance_0.4.0-beta.ova which introduces Advanced Setting for customizing the Docker Bridge Network. By default it will use `172.26.0.1/16` which is a default from Docker. 

![Screen Shot 2020-03-11 at 5 08 03 AM](https://user-images.githubusercontent.com/602199/76416454-5dc9ce80-6358-11ea-94e4-44f1c5168b83.png)

Here's example deploying VEBA overriding the default Docker Bridge Network using value of `172.30.0.1/16`

![Screen Shot 2020-03-11 at 5 08 21 AM](https://user-images.githubusercontent.com/602199/76416424-4e4a8580-6358-11ea-914d-5530eeec84a1.png)

Give this a try @virtualhobbit and let me know if it resolves the issue and unblocks you from giving VEBA a try in your env :)

**Comment by rhjensen79** [comment]
New version is working for me. None of the old versions were working, and I'm on a 172.17.x.x network. 
So I think I found out why. Thanks for the update.

**Comment by lamw** [comment]
@virtualhobbit Did you get a chance to verify yet?

**Comment by virtualhobbit** [comment]
Yup, can confirm this is now sorted with that build! Thanks @lamw!
