### ISSUE TITLE
[DOC] - Update the use case icons to VMware Corp Icons

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#740]
**Describe the bug**
Update the VEBA Use Case icons on homepage to VMware Corporate icons based on feedback from VMware Brand team

![Screen Shot 2021-12-10 at 3 08 18 PM 2](https://user-images.githubusercontent.com/602199/145653031-c6c88de5-e17f-42a8-9702-8f987c58645c.png)

**Comment by lamw** [comment]
Per PK - The graphics used for the Use Cases is actually based on CSS and not an image. We'll need to change the code to leverage the official brand approved graphics

**Comment by embano1** [comment]
Should this go into v0.7.2 or v0.8.0?

**Comment by lamw** [comment]
v0.8.0 as it'll require code changes

**Comment by pksrc** [comment]
I'll pick this up next week

**Comment by embano1** [comment]
Can we get this in for `v0.7.3`?
