### ISSUE TITLE
ImagePullPolicy is always "always" 

### ISSUE THREAD

**Issue by tranduyduong** [vmware-samples/vcenter-event-broker-appliance#753]
Hi,
I tried to set value for ImagePullPolicy as below
`functions:

  veba-echo2:

    lang: python3-http

    handler: ./echo

    image: local-veba-python-echo:1.0.1s

    imagePullPolicy: Never
    #image-pull-policy: Never

    environment:

      write_debug: false

      read_debug: false

    annotations:

      topic: "DrsVmPoweredOnEvent,VmPoweredOnEvent,VmPoweredOffEvent,VmReconfiguredEvent"`
But actually, the value of  ImagePullPolicy is always in deployment config of k8s. Can anyone let me know how to update this value via yaml file. Thank you for your reading

**Comment by embano1** [comment]
Hi, looks like you're using the deprecated OpenFaaS processor in VEBA. Can you please deploy VEBA with the default (Knative) processor and try our examples?

**Comment by tranduyduong** [comment]
Hi @embano1 , Many thanks for your quick comment. yes, I'm using OpenFaaS. I will try with Knative as you suggeted.

**Comment by lamw** [comment]
Closing this issue as Knative has been design to support air-gap env, so it shouldn't be pulling. If you run into any issues, you can file a new issue and/or reach out via our Slack
