### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by meyeaard** [vmware-samples/vcenter-event-broker-appliance#78]
Since the appliance is based on k8ts I understand that I could roll my own container platform to provide increased availability, but since this is being packaged as an easy to deploy appliance would it be possible to provide for HA in the product or via documentation?

Thoughts (again, I even hesitate to call myself a k8ts noob, I'm working on it though!)
1. In product?
  a. Deploy appliance as 3 node vApp?
  b. Keep existing single node OVA for simple deployments but provide a second OVA for preconfigured and ready to run additional nodes to create HA cluster.
2. In documentation?
  a. Documentation / howto to build out a k8tes cluster with your appliance OVA and additional nodes, possibly via vanilla PhotonOS OVAs.
  b. Possibly provide scripting to automate the PhotonOS / k8ts setup.

**Comment by lamw** [comment]
Thanks again for the feedback. The topic of availability is something we've discussed internally, it's more than just having a highly available infrastructure (whether that is hosting the VM and/or having replicas of the k8s application as you rightfully pointed out). There's also things like event delivery and what we can/should support which may also introduce or mandate additional changes. This is something we're still working through but open to feedback.

In terms of the appliance itself being made more available, I would say its probably not in scope as a Fling, totally get the ask but as mentioned in the previous issue, we have to prioritize our time against the core offering. There's certainly a class of functionality (updates, patching, backup etc.) that we probably won't be able to get to as a Fling but something I would expect from a Production solution if this were to be productized. Getting more feedback from customers on the core solution would help us make that ask. 

For #2 - There is an option to deploy VEBA outside of the current form factor, in fact that was one of the benefits we saw early on that Appliance was a nice and easy way to get this running in any environment without any k8s knowledge/expertise. We knew with Pacific around the corner or for folks with their own k8s cluster, you can certainly deploy the essence of VEBA which is a set of k8s apps. We don't have documentation on that yet but if this is interesting where you already have your own k8s cluster, we can certainly take this up as documentation enhancement?

**Comment by meyeaard** [comment]
Thank you again and I completely understand the Fling nature of things and priority for core services and I do appreciate your patience. Documentation would be completely acceptable for this esp as you point out with Pacific coming.

Aaron

________________________________

**Comment by pksrc** [comment]
A complete guide on how to achieve HA through a Kubernetes deployment is made available here - https://vmweventbroker.io/kb/advanced-deploy-k8s. @meyeaard  Let us know if this issue can be closed

**Comment by meyeaard** [comment]
Perfect, please close the issue, thank you for your attention to this!
