### ISSUE TITLE
Ability to change the pretext in an alert

### ISSUE THREAD

**Issue by MasterWayZ** [vmware-samples/vcenter-event-broker-appliance#784]
**Is your feature request related to a problem? Please describe.**
It would be nice if you can customize the `:rotating_light: Virtual Machine Alert from :veba: Knative Function :rotating_light:` message. Not only if you want a custom message, but it always displays this. Even in the situation where it fires this for an alarm was raised event on a non-VM object, like a ESXi host.

**Describe the solution you'd like**
The ability to customize the message, should you want to use a different text and/or different emojis.

**Describe alternatives you've considered**
N/A

**Additional context**
Will link another GitHub issue below once I made this, as there's another issue that is linked to this.

**Comment by kremerpatrick** [comment]
You can customize anything in a function by editing handler.ps1 and building a new container. Each function's README contains instructions on how to rebuild the container / reference a new container image.
