### ISSUE TITLE
Add Project Classification (Topics) to the Repository

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#804]
Add project classifications like e.g. serverless, faas, vmware, knative, kubernetes, etc. to the repo using [Topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics).

> With topics, you can explore repositories in a particular subject area, find projects to contribute to, and discover new solutions to a specific problem.

This will help the project to come up faster when searching for certain classifications on Github.

**Comment by embano1** [comment]
Done
