### ISSUE TITLE
Python Example itsdangerous 2.1.0

### ISSUE THREAD

**Issue by darrylcauldwell** [vmware-samples/vcenter-event-broker-appliance#806]
Since release of itsdangerous Python package 2.1.0 (Friday) I appear to be getting issue on running kn-py-echo example container "cannot import name 'json' from 'itsdangerous'". 

To workaround issue I specified itsdangerous PyPI version in requirements.txt to previous 2.0.1 and this appears to avoid issue. I haven't been able to establish what in 2.1.0 release is cause and suspect this will be a wider issue affecting other Flask applications.

**Comment by darrylcauldwell** [comment]
It looks like Flask 1.1.2 is unsupported and a more complete fix might be to uplift to 1.1.4 rather than pin to older itsdangerous.

**Comment by kremerpatrick** [comment]
@darrylcauldwell If you'd like to file the PR for this I can help you out, let me know.

**Comment by darrylcauldwell** [comment]
@kremerpatrick if/when I get this new Python function working with newer Flask version I'll try and loop back to retrofit and regression test the existing examples.

**Comment by embano1** [comment]
@darrylcauldwell we have a `v0.7.3` release coming. Do you think you can get a fix in by then?

**Comment by embano1** [comment]
@dsbibby 🙏

**Comment by dsbibby** [comment]
I can confirm this issue, plus another similar issue with Jinja2 2.11.3 when using Flask < 2.x

All existing Python example functions build and run with Flask 2.1.2 (latest), so I suggest updating to this version.

The kn-pay-echo function works as expected with Flask 2.1.2 and I’ll run functional tests for the other functions to confirm nothing breaks but expect not.

Should we be adding Flask’s dependencies to each functions requirements.txt to prevent similar in future?
