### ISSUE TITLE
VEBA Plug-in Installation Failed

### ISSUE THREAD

**Issue by rwlib3** [vmware-samples/vcenter-event-broker-appliance#819]
**Describe the bug**
vCenter 6.7U3 - VEBA-0.7.2 - VEBA Plug-in installation failed. Error downloading plug-in. Make sure that the URL is reachable and the registered thumbprint is correct. sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

**To Reproduce**
Deleted and reinstalled appliance - same issue

**Expected behavior**
VEBA Plug-in available via Administration/Client Plug-ins

**Screenshots**
![image](https://user-images.githubusercontent.com/37152147/159861112-c3dfcbea-be2d-48bb-8478-4adef6cfe7bf.png)
![image](https://user-images.githubusercontent.com/37152147/159860822-396e9ed9-2ffe-44f8-90eb-1ecc9017ec60.png)

**Version (please complete the following information):**
 - VEBA Form Factor: Appliance
 - VEBA Version: 0.7.2

**Additional context**
Appears to be a certificate issue to vCenter - internal CA signed cert. Full chain PEM and key added during OVA deployment for VEBA appliance.

**Comment by rwlib3** [comment]
any way to force the plug-in to reinstall? 

curl from vcenter appliance is successful per https://vmweventbroker.io/kb/troubleshoot-appliance

**Comment by embano1** [comment]
Hi @rwlib3 , sorry but the VEBA UI requires vCenter Server 7.0 or greater due to the required plugin registration process/API.
