### ISSUE TITLE
Use cases link update

### ISSUE THREAD

**Issue by kremerpatrick** [vmware-samples/vcenter-event-broker-appliance#820]
On https://vmweventbroker.io/kb/, the Community Use Cases link is broken. It should point to https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/development/USECASES.md

**Comment by embano1** [comment]
Same issue with [this](http://vmweventbroker.io/examples/knative) link in `http://vmweventbroker.io/kb/functions`:

> Users who directly want to jump into VMware vSp[here](http://vmweventbroker.io/examples/knative)-related function code might want to check out the examples we provide here <- broken.
