### ISSUE TITLE
[BUG] Website out of sync since `0.7.2` release

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#821]
**Describe the bug**

- [x] Broken due to https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error
- [x] Also add more prominent highlighting (in deployment/FAQ) requirement of VC v7.x for UI.
- [x] Update `4 vCPU and 8GB of memory for VMware Event Broker Appliance`

**Comment by embano1** [comment]
@lamw IIRC this would be correct: `6 vCPU and 8GB of memory for VMware Event Broker Appliance` ?

**Comment by lamw** [comment]
> @lamw IIRC this would be correct: `6 vCPU and 8GB of memory for VMware Event Broker Appliance` ?

Correct. See https://github.com/vmware-samples/vcenter-event-broker-appliance/blob/development/photon-version.json for config def
