### ISSUE TITLE
[BUG] Proxy Settings stop installation

### ISSUE THREAD

**Issue by jrsmile** [vmware-samples/vcenter-event-broker-appliance#824]
**Describe the bug**
When setting the proxy during ovf install the description of the proxy setting states it can be set with Quotes.
Unfortunately the installscript does not like this.
If you configure the Proxy like this : "http://proxy:port/"
the deployment script hangs and veba is not beeing installed.
this is because the Quotes close some variabe name in the installscript and you get a error.

**To Reproduce**
1.deploy the ovf 
2. In the Wizzard set a Proxy Server according to description.
3. Finish deployment wizard
4. Turn on VM and have a look at the console.

**Expected behavior**
The proxy is set corectly and kubernetes is beeing deployed.

**Version:**
 - VEBA Form Factor: Appliance
 - VEBA Version: 0.7.2

**Additional context**
There should be a check to accept both versions with and without quotes 
to clean the input before usage as variable in the script.

**Comment by dsbibby** [comment]
@lamw @embano1 - Happy to take a look at this if you like? I think it can be resolved by:
- Changing the description in the appliance deployment to remove the quotes from the example
- Adding some sanitization (i.e. trimming quotes and whitespace?) from the `getOvfProperty.py` script

**Comment by embano1** [comment]
> @lamw @embano1 - Happy to take a look at this if you like? I think it can be resolved by:
> 
> - Changing the description in the appliance deployment to remove the quotes from the example
> 
> - Adding some sanitization (i.e. trimming quotes and whitespace?) from the `getOvfProperty.py` script

Go for it 👍🤦🏻‍♂️

**Comment by dsbibby** [comment]
Yep, I was thinking that. Will sort something 🙂
