### ISSUE TITLE
Consistent user experience for example functions

### ISSUE THREAD

**Issue by embano1** [vmware-samples/vcenter-event-broker-appliance#83]
Check functions provided as examples for consistency on:

- docs
- events used (e.g. standardize on "DrsVmPoweredOnEvent,VmPoweredOnEvent") to address common issues in non-DRS enabled clusters
- naming (values in stack.yml, e.g. handlers, secrets, etc.)

**Comment by pksrc** [comment]
@embano1 Should i tackle this through our documentation?

**Comment by embano1** [comment]
PLEASE! But it would also be great if you could make changes to the examples provided in the repo so it‘s consistent across code/docs.

**Comment by embano1** [comment]
Could be merged with #209

**Comment by embano1** [comment]
#411
