### ISSUE TITLE
[DOC] Gitlab Registry

### ISSUE THREAD

**Issue by jrsmile** [vmware-samples/vcenter-event-broker-appliance#839]
@lamw @kremerpatrick 
thanks again for helping me out the other day.
i might have finally the answer to my problem getting gitlab as registry working with veba.

there is more to the initial problem then discovered, just to let anyone stumbling across this issue know, it seems it is currently not possible to use gitlab as registry with containerd. https://gitlab.com/gitlab-org/gitlab/-/issues/337184 it seems the implementation of the registry in gitlab is flawed.

**Comment by embano1** [comment]
Thx for the update @jrsmile . Shall we close this issue then?

**Comment by jrsmile** [comment]
Sure, was just for Dokumentation so nobody Else wastes his time with this Problem for Now.
