### ISSUE TITLE
Google container registry image missing for kn-pcli-ha-restarted-vms

### ISSUE THREAD

**Issue by kremerpatrick** [vmware-samples/vcenter-event-broker-appliance#880]
**Describe the bug**
Missing Google Container images

kn-pcli-ha-restarted-vms - us.gcr.io/daisy-284300/veba/kn-pcli-ha-restarted-vms:1.0

**To Reproduce**
docker pull us.gcr.io/daisy-284300/veba/kn-pcli-ha-restarted-vms:1.0
Error response from daemon: manifest for us.gcr.io/daisy-284300/veba/kn-pcli-ha-restarted-vms:1.0 not found: manifest unknown: Failed to fetch "1.0" from request "/v2/daisy-284300/veba/kn-pcli-ha-restarted-vms/manifests/1.0".

**Expected behavior**
Successful pull

**Comment by embano1** [comment]
Done, sorry for that.
