### ISSUE TITLE
Introduce /etc/veba-version

### ISSUE THREAD

**Issue by lamw** [vmware-samples/vcenter-event-broker-appliance#91]
For informational + debugging/troubleshooting purposes, there's no easy way of obtaining the version of VEBA from within the Appliance. Today, the version is only available outside of the VM in the VM Annotation field as well as the filename. If either of those change, then the version is lost and we still do not have a way to identify the release from within. 

Proposal is to introduce `/etc/veba-version` file which would be created on the filesystem and simply contain the version such as `v0.4`. I'm curious if there's other information we may want to capture @embano1?

**Comment by codegold79** [comment]
@lamw, would the event processor be placed in the `/etc/veba-version` file as well? If so, wouldn't the name be something less specific?

**Comment by lamw** [comment]
After our chat, I think /etc/veba-release would be better name. It’s good point on whether this file should be name something else if it contains processor detail. Maybe Michael has some thoughts given the two pieces of info we should persist somewhere

**Comment by embano1** [comment]
SGTM
