### ISSUE TITLE
Create a custom webhook function for Harbor

### ISSUE THREAD

**Issue by rguske** [vmware-samples/vcenter-event-broker-appliance#914]
**Is your feature request related to a problem? Please describe.**
Since Harbor is providing a [webhook feature](https://goharbor.io/docs/2.2.0/working-with-projects/project-configuration/configure-webhooks/) for each created project/repository, it'd be great to have a custom webhook-function available which provides us custom Harbor specific events like e.g. `com.vmware.harbor.artifact_pushed.v0`.

**Describe the solution you'd like**
By following @lamw's provided way to create a genereic webhook function [HERE](https://williamlam.com/2021/09/custom-webhook-function-to-publish-events-into-vmware-event-broker-appliance-veba.html), I was able to set up the webhook config in Harbor properly in order to send events to it.

Figure I:
![image](https://user-images.githubusercontent.com/31652019/174991373-50f515a4-71f3-47f8-82a6-e08f36317178.png)

When an event is sent based on an action such as e.g. `docker push`, the following very usable output appears in the webhook-deployment `user-container`.

`k -n vmware-functions logs kn-ps-webhook-00002-deployment-8f8664b49-6mhnl user-container`

```
user-container 06/22/2022 09:01:43 - Creating CloudEvent ...
user-container
user-container 06/22/2022 09:01:43 - [Headers]:
user-container
user-container Name                           Value
user-container ----                           -----
user-container X-Forwarded-For                {10.197.96.51, 10.10.0.1, 10.10.0.30
user-container Content-Type                   {application/json
user-container Forwarded                      {for=10.197.96.51;proto=http, for=10.10.0.1
user-container Host                           {kn-ps-webhook.vmware-functions.veba-dev.jarvis.tanzu
user-container User-Agent                     {Go-http-client/1.1
user-container X-Forwarded-Proto              {http
user-container X-Request-Id                   {94817867-aced-450b-a4d4-e046389e5475
user-container X-Envoy-Internal               {true
user-container Accept-Encoding                {gzip
user-container K-Proxy-Request                {activator
user-container Content-Length                 {448
user-container X-Request-Start                {t=1655888503.111
user-container
user-container
user-container 06/22/2022 09:01:43 - [Body]:
user-container
user-container @{type=PUSH_ARTIFACT; occur_at=1655888502; operator=admin; event_data=}
user-container
user-container 06/22/2022 09:01:43 - [CloudEvent]:
user-container
user-container DataContentType : application/json
user-container Data            : {123, 34, 116, 121…
user-container Id              : c025833f-7c0e-44b1-9926-52fa92c45443
user-container DataSchema      :
user-container Source          : 10.197.96.51
user-container SpecVersion     : V1_0
user-container Subject         :
user-container Time            : 06/22/2022 09:01:43
user-container Type            : com.vmware.generic.webhook.v0
user-container
user-container
user-container
user-container 06/22/2022 09:01:43 - Sending CloudEvent to VMware Event Broker ...
user-container
user-container 06/22/2022 09:01:43 - Successfully sent CloudEvent ...
user-container
```
Even better is the output in Sockeye 😃 

Figure II:

![image](https://user-images.githubusercontent.com/31652019/175265822-0f1a1f62-155e-43a2-bdc7-dff607a3c53e.png)

Let's create a function which gives us the possibility to process those custom events.

**Comment by huzai9527** [comment]
and then we found risk in the image, how can we tell harbor,  by using the api return, and what data should api return to harbor,  does the return data have offcial type?

**Comment by embano1** [comment]
IIUC your desired workflow is:

`harbor-event` -> `veba` -> `function`-> `harbor-api` -> `do_something` ?

**Comment by huzai9527** [comment]
HI @rguske , I only found the proposal here https://github.com/goharbor/community/blob/main/proposals/new/webhook.md, do we have specific documents?

**Comment by rguske** [comment]
> HI @rguske , I only found the proposal here https://github.com/goharbor/community/blob/main/proposals/new/webhook.md, do we have specific documents?

Regarding what?

**Comment by huzai9527** [comment]
when we found risk in the image we should tell harbor this image can't be pushed/pulled, what I confused is that what formate and what data should we  return to harbor

**Comment by embano1** [comment]
> when we found risk in the image we should tell harbor this image can't be pushed/pulled, what I confused is that what formate and what data should we  return to harbor

You need to make an API call to deactivate (delete) the image. Please see the Harbor API docs.

**Comment by huzai9527** [comment]
THANK YOU @embano1 ,  I got it,  In other words，when we use the post data from webhook，and indeed found risk from the image， then we should use harbor api to block this operation without by using the reponse from webhook.  different from docker authz plugin.

**Comment by embano1** [comment]
Yes, please see my comment above. VEBA is all about event-driven actions using functions. In your case, your VEBA function gets the CloudEvent we create with the webhook integration and then you can do whatever you want. For example send a note to Slack or call another API, eg Harbor.

**Comment by huzai9527** [comment]
sorry for miss https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/914#issuecomment-1164169261， THAKYOU VERY MUCH
