### ISSUE TITLE
Broken links to functions

### ISSUE THREAD

**Issue by allankjaer** [vmware-samples/vcenter-event-broker-appliance#927]
**Describe the bug**
Broken links to function from https://vmweventbroker.io/examples I have see that this is broken, there may be more.

![image](https://user-images.githubusercontent.com/65256499/179346274-dd0c043f-e9bf-4129-90c2-ff9813e130a7.png)

**Comment by embano1** [comment]
Thx for filing @allankjaer 

@kremerpatrick mind filing a PR to fix your functions? Those are the only ones affected due to using `url: "/tree/master/knative/powercli/kn-pcli-vds-config"` instead of `…master/examples/knative…` 🙏

**Comment by embano1** [comment]
@allankjaer I guess you found the documentation anyways then or do you need help?

**Comment by allankjaer** [comment]
Yes i found them.
