### ISSUE TITLE
VEBA UI and "ADD EVENT" [BUG] 

### ISSUE THREAD

**Issue by allankjaer** [vmware-samples/vcenter-event-broker-appliance#931]
**Describe the bug**
When I us the VEBA UI in vCenter, and I have deployed a function on a event, and afterward want's to add a 2nd event to that deployment, it do not work, the first one still work. it's the same for the 3rd...

**To Reproduce**
- create a function that can be used on multiple events
- deploy function on event in the VEBA UI, for example VmRemovedEvent
- In the VEBA UI use the "ADD EVENT" on the function, for example VmCreatedEvent

**Expected behavior**
Both Event trickers the function.
In version 0.7.1 this worked fine, did not test it in 0.7.2

**Screenshots**

**Version (please complete the following information):**
 - VEBA Appliance
 - VEBA Version:0.7.3

**Additional context**
I can see the function gets started on the VEBA Appliance with "kubectl get pods -n vmware-functions".
and in the UI can I see both events on the function.

I have for now created the same function for each event with different names as a works a workaround.

**Comment by embano1** [comment]
Thx @allankjaer for raising this! I asked the VEBA UI plugin developer to take a look at this.

**Comment by embano1** [comment]
@allankjaer issue found and we already got a fix. Will come back to this once we have a release plan.

**Comment by lamw** [comment]
@allankjaer - We've just created a pre-release for VEBA `v0.7.4` OVA, which you can grab at https://download3.vmware.com/software/vmw-tools/veba/VMware_Event_Broker_Appliance_release_0.7.4.ova

Let us know if you run into any issues before we make the release official

**Comment by allankjaer** [comment]
Hi William

I get an error message when trying to down the 0.7.4 pre-release.

This site can’t be reached

The webpage at https://download3.vmware.com/software/vmw-tools/veba/VMware_Event_Broker_Appliance_release_0.7.4.ova might be temporarily down or it may have moved permanently to a new web address.

ERR_INVALID_RESPONSE

//Allan
________________________________

**Comment by lamw** [comment]
@allankjaer sorry, looks like the URL was incorrect. I've just fixed it in original post. Should work now!

**Comment by allankjaer** [comment]
Hi William,

Just deployed it in the Lab, and deployed all my functions as usual, and everything looks good.

//Allan
________________________________
